-- INSERTS para a tabela public."tb_tipo_leito" com version_id = 2
-- Arquivo de origem: tb_tipo_leito.txt

INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('01', 'Cirúrgico', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('02', 'Obstétricos', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('03', 'Clínico', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('04', 'Crônicos', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('05', 'Psiquiatria', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('06', 'Pneumologia Sanitária (Tisiologia)', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('07', 'Pediátricos', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('08', 'Reabilitação', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('09', 'Leito Dia / Cirúrgicos', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('10', 'Leito Dia / Aids', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('11', 'Leito Dia / Fibrose Cística', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('12', 'Leito Dia / Intercorrência Pós-Transplante', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('13', 'Leito Dia / Geriatria', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('14', 'Leito Dia / Saúde Mental', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('17', 'Estabelecimento Exclusivo UTI SUS', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('51', 'UTI II ADULTO-SINDROME RESP. AGUDA GRAVE (SRAG)-COVID-19', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('52', 'UTI II PEDIATRICO-SINDROME RESP. AGUDA GRAVE (SRAG)-COVID-19', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('65', 'Unidade Intermediária Neonatal', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('74', 'UTI I', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('75', 'UTI Adulto II', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('76', 'UTI Adulto III', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('77', 'UTI Infantil I', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('78', 'UTI Infantil II', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('79', 'UTI Infantil III', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('80', 'UTI Neonatal I', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('81', 'UTI Neonatal II', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('82', 'UTI Neonatal III', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('83', 'UTI Queimados', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('84', 'Acolhimento Noturno', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('85', 'UTI Coronariana-UCO tipo II', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('86', 'UTI Coronariana-UCO tipo III', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('87', 'Saúde Mental (Clínico)', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('88', 'Queimado Adulto (Clínico)', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('89', 'Queimado Pediátrico (Clínico)', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('90', 'Queimado Adulto (Cirúrgico)', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('91', 'Queimado Pediátrico (Cirúrgico)', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('92', 'UCI Unidade de Cuidados Intermediarios Neonatal Convencional', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('93', 'UCI Unidade de Cuidados Intermediarios Neonatal Canguru', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('94', 'UCI Unidade de Cuidados Intermediarios Pediatrico', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('95', 'UCI Unidade de Cuidados Intermediarios Adulto', '202505', 2);
INSERT INTO public."tb_tipo_leito" ("co_tipo_leito", "no_tipo_leito", "dt_competencia", "version_id") VALUES ('96', 'Suporte Ventilatório Pulmonar', '202505', 2);
