-- INSERTS para a tabela public."tb_descricao_detalhe" com version_id = 5
-- Coluna 'id' deve ser BIGSERIAL e será auto-preenchida pelo banco.
-- Arquivo de origem: tb_descricao_detalhe.txt

INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('001', 'DESTINA-SE A IDENTIFICAR SE NO VALOR DO PROCEDIMENTO JÁ ESTÁ INCLUSO QUALQUER TIPO DE ANESTESIA, EXCETO ANESTESIA LOCAL, POIS ESTA JÁ ESTÁ INCLUSA NO VALOR DO PROCEDIMENTO. ||NOS PROCEDIMENTOS HOSPITALARES COM O ATRIBUTO "INCLUI ANESTESIA" SIGNIFICA QUE O VALOR DA ANESTESIA ESTÁ INCLUÍDO NO COMPONENTE SP (SERVIÇOS PROFISSIONAIS), NÃO PERMITINDO O REGISTRO DE CÓDIGOS DE ANESTESIA EM SEPARADO, DO PROCEDIMENTO PRINCIPAL. NOS PROCEDIMENTOS AMBULATORIAIS, COM O ATRIBUTO "INCLUI ANESTESIA" SIGNIFICA QUE O VALOR DA ANESTESIA ESTÁ INCLUÍDO NO COMPONENTE SA (SERVIÇO AMBULATORIAL). ||', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('003', 'IDENTIFICA OS PROCEDIMENTOS QUE PERMITEM O REGISTRO NA AIH DE CONTINUIDADE, OU SEJA, LONGA PERMANÊNCIA.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('004', 'INDICA QUE PELAS CARACTERÍSTICAS PRÓPRIAS DO PROCEDIMENTO OU PELA CONDIÇÃO CLÍNICA DO PACIENTE ADMITE DIAS DE PERMANÊNCIA ALÉM DO DOBRO DOS DIAS PREVISTOS NO ATRIBUTO -"MÉDIA DE PERMANÊNCIA". NESSE CASO É NECESSÁRIO O REGISTRO NA AIH DO CÓDIGO DE PROCEDIMENTO 08.02.01.019-9.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('005', 'IDENTIFICA OS PROCEDIMENTOS QUE ADMITEM LIBERAÇÃO PELO GESTOR DE SAÚDE LOCAL, DE QUANTIDADE SUPERIOR A DEFINIDA EM SEU ATRIBUTO QUANTIDADE MÁXIMA.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('006', 'IDENTIFICA OS PROCEDIMENTOS QUE INTEGRAM A POLÍTICA NACIONAL DE REGULAÇÃO DE ALTA COMPLEXIDADE, INSTITUÍDOS EM PORTARIAS ESPECÍFICAS.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('007', 'PROCEDIMENTOS CUJO VALOR É FIXADO POR DIA DE INTERNAÇÃO E, PORTANTO, NÃO TÊM MÉDIA DE PERMANÊNCIA DEFINIDA E SIM NÚMERO MÁXIMO DE DIAS DE INTERNAÇÃO A SEREM REGISTRADAS NA AIH.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('008', 'IDENTIFICA OS PROCEDIMENTOS PRINCIPAIS QUE POR CARACTERÍSTICAS DO ATENDIMENTO NÃO É PERMITIDO ALTERAR O PROCEDIMENTO PRINCIPAL SOLICITADO/AUTORIZADO NO LAUDO.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('009', 'Identifica os procedimentos que exigem identificação do usuário pelo Cadastro de Pessoa Física (CPF), preferencialmente, ou pelo Cartão Nacional de Saúde (CNS).', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('011', 'IDENTIFICA OS PROCEDIMENTOS PARA OS QUAIS O PACIENTE PODE RECEBER ALTA HOSPITALAR DIRETAMENTE DO LEITO DA UTI, NÃO SENDO EXIGIDA A SUA PERMANÊNCIA EM LEITO DE ENFERMARIA APÓS A ALTA DA UTI.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('012', 'IDENTIFICA OS PROCEDIMENTOS QUE EXIGEM O REGISTRO DA IDADE DOS USUÁRIOS ATENDIDOS.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('013', 'IDENTIFICA OS PROCEDIMENTOS PARA OS QUAIS DEVE SER VERIFICADA, NO CNES, A EXISTÊNCIA DE HABILITAÇÃO DO ESTABELECIMENTO TERCEIRIZADO.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('014', 'IDENTIFICA OS PROCEDIMENTOS DE TRATAMENTO CONTÍNUO PERMITIDOS EM APAC DE CONTINUIDADE.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('015', 'IDENTIFICA OS PROCEDIMENTOS QUE PODERÃO SER INFORMADOS APENAS PELOS ESTABELECIMENTOS DE SAÚDE IDENTIFICADOS NO CNES COMO SENDO DO TIPO HOSPITAL ESPECIALIZADO COM SUBTIPO DE ESTABELECIMENTO EM PSIQUIATRIA (07.06).', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('017', 'IDENTIFICA OS PROCEDIMENTOS QUE NÃO PODEM SER REALIZADOS SEM O REGISTRO DE OPM.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('020', 'IDENTIFICA, PARA FINS DE MONITORAMENTO, OS PROCEDIMENTOS QUE INTEGRAM O ROL DE PROCEDIMENTOS PASSÍVEIS DE SEREM REALIZADOS NO CENTRO DE ESPECIALIDADE ODONTOLÓGICA, DEFINIDOS EM PORTARIA ESPECÍFICA.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('021', 'IDENTIFICA OS PROCEDIMENTOS QUE NÃO EXIGEM A INFORMAÇÃO DE CBO.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('022', 'Identifica os procedimentos na APAC que exigem preenchimento de dados complementares.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('023', 'Identifica os procedimentos em que o registro é efetuado exclusivamente no SISCOLO.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('024', 'Identifica os procedimentos em que o registro é efetuado exclusivamente no SISPRENATAL.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('025', 'Identifica os procedimentos em que o registro é efetuado exclusivamente no SISMAMA.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('026', 'Identifica o procedimento que exige registro de procedimentos secundários compativeis.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('029', 'Procedimentos que admitem a apresentação de até cinco competências anteriores.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('033', 'Identifica que a validade da APAC é fixada em 03 competencias. Em caso de necessidade de fechar na primeira competencia, terá que ser fechado em definitivo.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('034', 'Identifica os procedimentos que não exigem identificação do usuário pelo Cadastro de Pessoa Física (CPF) ou pelo Cartão Nacional de Saúde (CNS);', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('036', 'Identifica que o procediemnto que tem o Instrumento de Registro RASS, exige autorização.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('037', 'Identifica que é necessário a informação do fornecedor para os referidos procediementos.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('038', 'Exige preenchimento dos campos serviço/classificação no momento do registro do procedimento.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('040', 'Identifica os procedimentos em que o registro é efetuado obrigatoriamente no SISCAN.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('041', 'Identifica que a validade da APAC é fixada em 12 competencias. Em caso de necessidade de fechar na primeira competencia, terá que ser fechado em definitivo.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('042', 'PROCEDIMENTOS QUE ESTIVEREM MARCADOS COM ESTE ATRIBUTO NÃO PODERÃO SER LIBERADOS DESTA CRÍTICA PELO GESTOR.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('043', 'ESTE ATRIBUTO INDICA QUE, AO REGISTRAR O PROCEDIMENTO, É OBRIGATÓRIO INFORMAR OS CID DE CAUSAS ASSOCIADAS.||||', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('044', 'PROCEDIMENTOS CIRÚRGICOS ELETIVOS DE MÉDIA COMPLEXIDADE REDEFINIDOS PELA PORTARIA/GM N° 1.294, DE 25 DE MAIO DE 2017.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('045', 'Diárias de leitos complementares	São leitos de internação destinados a pacientes que necessitam de assistência especializada exigindo características especiais, tais como: as unidades de isolamento reverso e as unidades de Tratamento intensiva e semi-intensiva. Este atributo foi inserido para atender ao CMD.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('046', 'Atributo criado para atender ao CMD. Só serão vinculados aos procedimentos quando passar a valer no RTS.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('047', 'Atributo inserido para atender ao CMD. Os procedimentos só serão vinculados quando estiver funcionando no RTS.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('048', 'Obrigatório registro de CID.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('049', 'Permite registrar equipe Cirúrgica.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('050', 'Atributo que identifica o registro do número do Cartão Nacional de Saúde do recém-nascido no Conjunto Mínimo de Dados-CMD.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('051', 'Organizar e ampliar o acesso para redução das filas para procedimentos Cirúrgicos da Atenção Especializada (Eletivos).', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('052', 'Para o programa das Eletiva', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('053', 'Programa Mais Acesso a Especialistas (PMAE): Identifica os procedimentos integrantes do PMAE, que objetiva a qualificação e a ampliação do acesso a consultas, exames e outros procedimentos diagnósticos e terapêuticos na Atenção Ambulatorial Especializada à Saúde.', '202501', 5);
INSERT INTO public."tb_descricao_detalhe" ("co_detalhe", "ds_detalhe", "dt_competencia", "version_id") VALUES ('054', 'Identifica que a validade da APAC é de, no máximo, 02 competências e não admite APAC de continuidade.', '202501', 5);
