-- INSERTS para a tabela public."tb_servico" com version_id = 5
-- Coluna 'id' deve ser BIGSERIAL e será auto-preenchida pelo banco.
-- Arquivo de origem: tb_servico.txt

INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('100', 'Serviço de Atenção a Saúde no Sistema Penitenciário', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('101', 'Estratégia de Saúde da Família', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('102', 'Estratégias de Agentes Comunitário de Saúde', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('103', 'Serviço de Atendimento Móvel de Urgências', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('104', 'Regulação Assistêncial dos Serviços de Saúde', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('105', 'Serviço de Atenção em Neurologia/ Neurocirurgia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('106', 'Serviço de Atenção a DST/HIV/AIDS', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('107', 'Atenção à Saúde Auditiva', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('108', 'Atenção a Saúde do Trabalhador', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('109', 'Serviço de Atenção a Saúde dos Adolecentes em Conflito com a Lei, em Regime de Internação e Internação Provisória', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('110', 'Serviço de Atenção a Saúde Reprodutiva', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('111', 'Serviço de Atenção ao Paciente com Tuberculose', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('112', 'Serviço de Atenção ao Pré-Natal e Nascimento', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('113', 'Serviço de Atenção Domiciliar', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('114', 'Serviço de Atenção em Saúde Bucal', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('115', 'Serviço de Atenção Psicossocial', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('116', 'Serviço de Atenção Cardiovascular/Cardiologia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('117', 'Serviço de Cirurgia Reparadora', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('118', 'Serviço de Cirurgia Torácica', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('119', 'Serviço de Controle de Tabagismo', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('120', 'Serviço de Diagnóstico por Anatomia Patológica e/ou Citopatologia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('121', 'Diagnóstico por Imagem', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('122', 'Serviço de Diagnóstico por Métodos Gráficos/Dinâmicos', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('123', 'Serviço de Dispensação de Órteses, Próteses e Materiais Especiais', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('124', 'Serviço de Endocrinologia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('125', 'Serviço de Farmácia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('126', 'Serviço de Fisioterapia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('127', 'Serviço de Atenção à Obesidade', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('128', 'Serviço de Hemoterapia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('129', 'Servico de Laboratório de Histocompatibilidade', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('130', 'Atenção à Doença Renal Crônica', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('131', 'Serviço de Oftalmologia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('132', 'Serviço de Oncologia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('133', 'Serviço de Pneumologia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('134', 'Serviço de Práticas Integrativas e Complementares', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('135', 'Serviço de Reabilitação', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('136', 'Serviço de Suporte Nutricional', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('137', 'Serviço de Telemedicina', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('138', 'Serviço de Traumato-Ortopedia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('139', 'Serviço de Triagem Neonatal', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('140', 'Serviço de Urgência e Emergência', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('141', 'Serviço de Vigilância em Saúde', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('142', 'Serviço de Endoscopia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('143', 'Serviço Móvel de Urgência (exceto SAMU)', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('144', 'Serviço Posto de Coleta de Materiais Biológicos', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('145', 'Serviço de Diagnóstico por Laboratório Clínico', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('146', 'Serviço de Videolaparoscopia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('147', 'Serviço de Apoio a Saúde da Família', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('148', 'Hospital-Dia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('149', 'Transplante', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('150', 'Cirurgia Vascular', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('151', 'Medicina Nuclear', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('152', 'Atenção à Saúde da População Indígena', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('153', 'Atenção Especializada no Processo Transexualizador', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('154', 'Serviço de Banco de Tecidos', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('155', 'Serviço de Traumatologia  Ortopedia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('157', 'Serviço de Laboratorio de Protese Dentaria', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('158', 'Serviço de Atenção Integral em Hanseniase', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('159', 'Atenção Primária', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('160', 'Teleconsultoria', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('161', 'Consultório na Rua', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('162', 'Serviço de Terapia Intensiva', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('163', 'Serviço de Cuidados Intermediários', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('164', 'Serviço de Órteses,Próteses e Materiais Especiais em Reabilitação', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('165', 'Atenção às Pessoas em Situação de Violência Sexual', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('166', 'Serviço de  Análise Laboratorial  de Produtos Sujeitos á  Vigilância Sanitária', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('167', 'Atendimento Itinerante de Asistência e Ensino em Saúde', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('168', 'Atenção Às Pessoas com Doenças Raras', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('169', 'Serviço de Atenção em Urologia', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('170', 'Comissões e Comitês', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('171', 'Cuidados Paliativos', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('173', 'Logística de Imunobiológicos', '202501', 5);
INSERT INTO public."tb_servico" ("co_servico", "no_servico", "dt_competencia", "version_id") VALUES ('174', 'Imunização', '202501', 5);
