-- Script SQL INSERT para a tabela: tb_servico_classificacao
-- Gerado a partir do arquivo de dados: tb_servico_classificacao.txt (Encoding Leitura: latin-1)
-- Usando version_id: 1
-- Data de geração: 2025-05-12 21:55:55

INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (1, 1, '168', '001', 'Atenção Especializada Em Doenças Raras', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (2, 1, '169', '001', 'Urologia em Geral', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (3, 1, '170', '001', 'Núcleo de Segurança do Paciente', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (4, 1, '171', '001', 'Apoio Assistencial', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (5, 1, '173', '001', 'Recebimento e Inspeção', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (6, 1, '174', '001', 'Indivíduos em Geral', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (7, 1, '100', '001', 'Atendimento em presídio até 100 presos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (8, 1, '101', '001', 'Saúde da família', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (9, 1, '102', '001', 'Estratégia de Agentes Comunitários de Saúde - EACS', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (10, 1, '103', '001', 'Ambulância de transporte', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (11, 1, '104', '001', 'Central de Regulação de Internações Hospitalares', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (12, 1, '105', '001', 'Neurocirurgia do trauma e anomalias do desenvolvimento', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (13, 1, '106', '001', 'Testagem e aconselhamento', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (14, 1, '108', '001', 'Atendimento Assistencial', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (15, 1, '109', '001', 'Unidade sócio-educativa com até 40 adolecentes', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (16, 1, '110', '001', 'Atenção à infertilidade', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (17, 1, '111', '001', 'Diagnóstico e tratamento', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (18, 1, '112', '001', 'Acompanhamento do pré-natal de risco habitual', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (19, 1, '113', '001', 'Assitência Domiciliar', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (20, 1, '114', '001', 'Dentística', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (21, 1, '115', '001', 'Residência terapêutica em saúde mental', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (22, 1, '116', '001', 'Eletrofisiologia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (23, 1, '117', '001', 'Tratamento da lipodistrofia do portador de HIV / AIDS', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (24, 1, '118', '001', 'Cirurgia torácica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (25, 1, '119', '001', 'Abordagem e tratamento do fumante', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (26, 1, '120', '001', 'Exames anatomopatológicos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (27, 1, '121', '001', 'Radiologia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (28, 1, '122', '001', 'Teste Ergométrico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (29, 1, '124', '001', 'Diagnóstico/Tratamento das doenças endócrinas, metabólicas e nutricionais', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (30, 1, '125', '001', 'Dispensação de Medicamentos do Componente Especializado da Assistência Farmaceutica.', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (31, 1, '126', '001', 'Assistência fisioterapêutica em alterações obstétricas, neonatais e uroginecológicas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (32, 1, '127', '001', 'Tratamento clínico, cirúrgico, reparador e acompanhamento ao obeso', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (33, 1, '128', '001', 'Procedimentos destinados à obtenção do sangue para fins de assitência hemoterápica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (34, 1, '129', '001', 'Exames de histocompatibilidade por meio de sorologia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (35, 1, '130', '001', 'Tratamento Dialítico-Hemodiálise', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (36, 1, '131', '001', 'Diagnóstico em oftalmologia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (37, 1, '132', '001', 'Oncologia pediátrica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (38, 1, '133', '001', 'Tratamento de Doenças das Vias Aéreas Inferiores', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (39, 1, '134', '001', 'Acupuntura', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (40, 1, '135', '001', 'Reabilitação Visual', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (41, 1, '136', '001', 'Enteral', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (42, 1, '137', '001', 'Exame eletrocardiográfico por telemedicina', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (43, 1, '138', '001', 'Diagnóstico e tratamento em cintura escapular', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (44, 1, '139', '001', 'Tratamento de recém-nascido com hipotireoidismo e fenilcetonuria', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (45, 1, '141', '001', 'Vigilância epidemiológica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (46, 1, '142', '001', 'Do aparelho digestivo', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (47, 1, '143', '001', 'Transporte terrestre', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (48, 1, '144', '001', 'Coleta realizada fora das estrutura laboratorial', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (49, 1, '145', '001', 'Exames Bioquimicos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (50, 1, '146', '001', 'Diagnóstica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (51, 1, '147', '001', 'NASF 1', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (52, 1, '148', '001', 'Saúde mental', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (53, 1, '149', '001', 'Rim', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (54, 1, '150', '001', 'Fístula arteriovenosa sem enxerto', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (55, 1, '151', '001', 'Medicina nuclear in vivo', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (56, 1, '152', '001', 'Atenção Básica à Populações Indígenas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (57, 1, '153', '001', 'Acompanhamento Clínico, pré e pós operatório e hormonioterapia.', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (58, 1, '154', '001', 'Banco de valvula cardiaca humana', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (59, 1, '155', '001', 'Serviço de Traumatologia e Ortopedia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (60, 1, '157', '001', 'Laboratorio Regional de Protese Dentaria', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (61, 1, '158', '001', 'Serviço de Atenção Integral em Hanseniase Tipo I', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (62, 1, '159', '001', 'Atenção Primária', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (63, 1, '160', '001', 'Teleconsultoria Assíncrona', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (64, 1, '161', '001', 'Equipe de Consultório na Rua - Modalidade I', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (65, 1, '162', '001', 'ADULTO', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (66, 1, '163', '001', 'NEONATAL CONVENCIONAL', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (67, 1, '164', '001', 'Dispensação de OPM Auxiliares de Locomoção e Ortopédicas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (68, 1, '165', '001', 'Referência para Atenção Integral às Pessoas em Situação de Violência Sexual', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (69, 1, '166', '001', 'Água de Consumo', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (70, 1, '167', '001', 'ODONTOLOGIA - PROJETO SAÚDE NA ESCOLA (PSE)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (71, 1, '100', '002', 'Atendimento em manicômio até 100 presos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (72, 1, '101', '002', 'Saúde bucal MI', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (73, 1, '102', '002', 'Estratégia de Agentes Comunitários de Saúde com Saúde Bucal - (modalidade I)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (74, 1, '103', '002', 'Unidade de suporte básico de vida terrestre (USB)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (75, 1, '104', '002', 'Cental de Regulação de Consultas e Exames', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (76, 1, '105', '002', 'Coluna e nervos periféricos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (77, 1, '106', '002', 'Diagnóstico e tratamento', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (78, 1, '108', '002', 'Centro de referência em saúde do trabalhador CEREST estadual', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (79, 1, '109', '002', 'Unidade sócio-educativa com de 41 a 100 adolecentes', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (80, 1, '110', '002', 'Contracepção clínica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (81, 1, '111', '002', 'Tratamento multidrogas resistentes', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (82, 1, '112', '002', 'Acompanhamento do pré-natal de alto risco', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (83, 1, '113', '002', 'Internação Domiciliar', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (84, 1, '114', '002', 'Endodontia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (85, 1, '115', '002', 'Atendimento psicossocial', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (86, 1, '116', '002', 'Cirurgia cardiovascular (adulto)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (87, 1, '117', '002', 'Tratamento em queimados', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (88, 1, '120', '002', 'Exames citopatológicos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (89, 1, '121', '002', 'Ultra-sonografia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (90, 1, '122', '002', 'Teste de Holter', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (91, 1, '124', '002', 'Cirurgia de glândulas endócrinas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (92, 1, '125', '002', 'Farmácia Popular', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (93, 1, '126', '002', 'Assistência fisioterapêutica em alterações oncológicas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (94, 1, '128', '002', 'Diagnóstico em hemoterapia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (95, 1, '129', '002', 'Exames de histocompatibilidade por sorologia e biologia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (96, 1, '131', '002', 'Tratamento clínico do aparelho da visão', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (97, 1, '132', '002', 'Hematologia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (98, 1, '133', '002', 'Diagnóstico em Pneumologia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (99, 1, '134', '002', 'Fitoterapia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (100, 1, '135', '002', 'Reabilitação Intelectual', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (101, 1, '136', '002', 'Enteral/Parenteral', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (102, 1, '138', '002', 'Diagnóstico e tratamento em membros superiores', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (103, 1, '139', '002', 'Tratamento de recém-nascido com doenças falciformes', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (104, 1, '141', '002', 'Vigilância sanitária', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (105, 1, '142', '002', 'Do aparelho respiratório', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (106, 1, '143', '002', 'Transporte aéreo', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (107, 1, '145', '002', 'Exames hematológicos e hemostasia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (108, 1, '146', '002', 'Cirúrgica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (109, 1, '147', '002', 'NASF 2', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (110, 1, '148', '002', 'AIDS', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (111, 1, '149', '002', 'Medula óssea', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (112, 1, '150', '002', 'Fístula arteriovenosa com enxerto', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (113, 1, '151', '002', 'Medicina nuclear in vitro', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (114, 1, '153', '002', 'Cirurgia e Acompanhamento pré e pós oreratório', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (115, 1, '154', '002', 'Banco de tecido musculo esqueletico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (116, 1, '155', '002', 'Serviço de Traumatologia e Ortopedia Pediátrica (até 21 anos de idade)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (117, 1, '158', '002', 'Serviço de Atenção Integral em Hanseniase Tipo II', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (118, 1, '159', '002', 'Atenção Básica com Saúde Bucal', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (119, 1, '160', '002', 'Teleconsultoria Síncrona', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (120, 1, '161', '002', 'Equipe de Consultório na Rua - Modalidade II', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (121, 1, '162', '002', 'NEONATAL', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (122, 1, '163', '002', 'NEONATAL CANGURU', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (123, 1, '164', '002', 'Manutenção e Adaptação de OPM Auxiliares de Locomoção e Ortopédicas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (124, 1, '165', '002', 'Serviço de Referência para Atenção Integral à Saúde de Adolescentes em Situação de Violência Sexual', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (125, 1, '166', '002', 'Água de Ambiental', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (126, 1, '167', '002', 'ODONTOLOGIA - PROJETO BRASIL ALFABETIZADO (PBA)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (127, 1, '168', '002', 'Referência em Doenças Raras', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (128, 1, '169', '002', 'Litotripsia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (129, 1, '171', '002', 'Apoio Matricial', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (130, 1, '173', '002', 'Armazenamento e Controle', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (131, 1, '174', '002', 'Grupos Especiais', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (132, 1, '164', '003', 'Dispensação de OPM Ortopédica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (133, 1, '116', '003', 'Cirurgia cardiovascular (Pediátrico)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (134, 1, '166', '003', 'Água de Hemodiálise', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (135, 1, '167', '003', 'OFTALMOLOGIA - PROJETO SAÚDE NA ESCOLA (PSE)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (136, 1, '173', '003', 'Distribuição', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (137, 1, '139', '003', 'Tratamento de recém-nascido com fibrose cística', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (138, 1, '141', '003', 'Vigilância ambiental', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (139, 1, '142', '003', 'Do aparelho urinário', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (140, 1, '143', '003', 'Transporte marítimo', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (141, 1, '145', '003', 'Exames sorológicos e imunológicos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (142, 1, '147', '003', 'NASF Intermunicipal', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (143, 1, '148', '003', 'Geriátrico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (144, 1, '149', '003', 'Coração', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (145, 1, '151', '003', 'Medicina nuclear in vivo por telemedicina', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (146, 1, '155', '003', 'Serviço de Traumatologia e Ortopedia de Urgência', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (147, 1, '158', '003', 'Serviço de Atenção Integral em Hanseniase Tipo III', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (148, 1, '159', '003', 'Academia da Saúde', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (149, 1, '160', '003', 'Segunda Opinião Formativa', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (150, 1, '161', '003', 'Equipe de Consultório na Rua - Modalidade III', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (151, 1, '162', '003', 'PEDIÁTRICO', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (152, 1, '163', '003', 'PEDIÁTRICO', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (153, 1, '117', '003', 'Tratamento da lipoatrofia facial do portador de HIV / AIDS', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (154, 1, '120', '003', 'Monitoramento Externo da Qualidade dos Exames Citopatologicos do Colo do Útero', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (155, 1, '121', '003', 'Tomografia computadorizada', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (156, 1, '122', '003', 'Exame Eletrocardiográfico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (157, 1, '125', '003', 'Farmácia com manipulação homeopática', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (158, 1, '126', '003', 'Assistência fisioterapêutica em oftalmologia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (159, 1, '128', '003', 'Procedimentos especiais em hemoterapia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (160, 1, '130', '003', 'Confeccção/Intervenção de Acessos para Diálise', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (161, 1, '131', '003', 'Tratamento cirúrgico do aparelho da visão', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (162, 1, '132', '003', 'Oncologia clínica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (163, 1, '133', '003', 'Diagnóstico em Pneumologia por Telemedicina', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (164, 1, '134', '003', 'Outras Práticas em Medicina Tradicional Chinesa', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (165, 1, '135', '003', 'Reabilitação Física', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (166, 1, '136', '003', 'Enteral/Parenteral, com manipulação/fabricação', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (167, 1, '138', '003', 'Diagnóstico e tratamento em coluna vertebral e caixa torácica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (168, 1, '100', '003', 'Atendimento em presídio acima de 100 presos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (169, 1, '101', '003', 'Saúde bucal MII', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (170, 1, '102', '003', 'Estratégia de Agentes Comunitários de Saúde com Saúde Bucal - (modalidade II)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (171, 1, '103', '003', 'Unidade de suporte avançado de vida terrestre (USA)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (172, 1, '104', '003', 'Central de Regulação de Urgências', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (173, 1, '105', '003', 'Tumores do sistema nervoso', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (174, 1, '106', '003', 'Diagnóstico, tratamento e capacitação técnica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (175, 1, '108', '003', 'Vigilância em Saúde do Trabalhador (VISAT)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (176, 1, '109', '003', 'Unidade sócio-educativa com de 101 a 180 adolecentes', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (177, 1, '110', '003', 'Laqueadura', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (178, 1, '112', '003', 'Parto em gestação de risco habitual', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (179, 1, '113', '003', 'Equipe Multidisciplinar de Atenção Domiciliar - EMAD', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (180, 1, '114', '003', 'Periodontia clínica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (181, 1, '115', '003', 'Serviço Hospitalar para Atenção a Saúde Mental', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (182, 1, '165', '003', 'Serviço de Referência para Atenção Integral à Saúde de Crianças em Situação de Violência Sexual', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (183, 1, '163', '004', 'ADULTO', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (184, 1, '164', '004', 'Manutenção e Adaptação de OPM Ortopédica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (185, 1, '165', '004', 'Serviço de Referência para Atenção Integral à Saúde de Homens em Situação de Violência Sexual', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (186, 1, '166', '004', 'Água Mineral', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (187, 1, '167', '004', 'OFTALMOLOGIA - PROJETO BRASIL ALFABETIZADO (PBA)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (188, 1, '173', '004', 'Transporte', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (189, 1, '139', '004', 'Tratamento de recém-nascido com outras doenças congênitas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (190, 1, '140', '004', 'Estabilização de paciente crítico/grave', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (191, 1, '141', '004', 'Núcleo de vigilância hospitalar', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (192, 1, '142', '004', 'Do aparelho ginecológico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (193, 1, '145', '004', 'Exames coprológicos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (194, 1, '147', '004', 'NASF 3', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (195, 1, '148', '004', 'Fibrose cística', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (196, 1, '149', '004', 'Pulmão', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (197, 1, '152', '004', 'Saneamento a Populações Indígenas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (198, 1, '159', '004', 'Estratégia de Saúde da Família', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (199, 1, '160', '004', 'TELEDIAGNOSTICO', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (200, 1, '162', '004', 'QUEIMADOS', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (201, 1, '116', '004', 'Cirurgia vascular', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (202, 1, '121', '004', 'Ressonância magnética', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (203, 1, '122', '004', 'Exame Eletroencefalográfico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (204, 1, '125', '004', 'Dispensação de medicamentos estratégicos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (205, 1, '126', '004', 'Assistência fisioterapêutica cardiovasculares e pneumo-funcionais', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (206, 1, '128', '004', 'Medicina transfusional', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (207, 1, '130', '004', 'Tratamento Nefrologia em Geral', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (208, 1, '131', '004', 'Projeto Olhar Brasil', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (209, 1, '132', '004', 'Radioterapia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (210, 1, '134', '004', 'Práticas Corpo-mente', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (211, 1, '135', '004', 'Reabilitação visual/mental/múltiplas deficiências', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (212, 1, '138', '004', 'Diagnóstico e tratamento em cintura pélvica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (213, 1, '100', '004', 'Atendimento em manicômio acima de 100 presos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (214, 1, '101', '004', 'Saúde da Família para a População Ribeirinha', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (215, 1, '104', '004', 'Unidade de autorizações de TFD intermunicipais', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (216, 1, '105', '004', 'Neurocirurgia vascular', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (217, 1, '106', '004', 'Assistência Domiciliar Terapêutica em AIDS-ADT', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (218, 1, '107', '004', 'Diagnóstico em Audiologia/Otologia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (219, 1, '109', '004', 'Unidade sócio-educativa com mais de 180 adolecentes', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (220, 1, '110', '004', 'Vasectomia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (221, 1, '112', '004', 'Parto em gestação de alto risco', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (222, 1, '113', '004', 'Equipe Multidisciplinar de Apoio - EMAP', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (223, 1, '114', '004', 'Moldagem/Manutenção', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (224, 1, '115', '004', 'Serviço Residencial Terapêutico Tipo I - SRT tipo I', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (225, 1, '164', '005', 'Dispensação de OPM Auditiva', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (226, 1, '115', '005', 'Serviço Residencial Terapêutico Tipo II - SRT tipo II', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (227, 1, '166', '005', 'Alimentos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (228, 1, '138', '005', 'Diagnóstico e tratamento em membros inferiores', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (229, 1, '139', '005', 'Acompanhamento a pacientes com diagnósticos de Hiperplasia Adrenal Congênita', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (230, 1, '140', '005', 'Atendimento ao paciente com Acidente Vascular Cerebral (AVC)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (231, 1, '141', '005', 'Vigilância de Zoonoses', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (232, 1, '145', '005', 'Exames de uroanálise', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (233, 1, '148', '005', 'Cirúrgico / Diagnóstico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (234, 1, '149', '005', 'Córnea / Esclera', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (235, 1, '152', '005', 'Atenção Especializada a Populações Indígenas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (236, 1, '159', '005', 'Saúde Bucal', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (237, 1, '160', '005', 'TELE-EDUCACAO', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (238, 1, '162', '005', 'DOENÇA CORONARIANA (UCO)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (239, 1, '116', '005', 'Cardiologia intervencionista (hemodinâmica)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (240, 1, '122', '005', 'Teste Ergométrico por Telemedicina', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (241, 1, '125', '005', 'Dispensação de medicamentos básicos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (242, 1, '126', '005', 'Assistência fisioterapêutica nas disfunções músculo-esqueléticas (todas as origens)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (243, 1, '130', '005', 'Tratamento Diálitico Peritonial', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (244, 1, '131', '005', 'Diagnóstico em Oftalmologia por Telemedicina', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (245, 1, '132', '005', 'Oncologia cirúrgica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (246, 1, '134', '005', 'Homeopatia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (247, 1, '135', '005', 'Reabiliatação Auditiva', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (248, 1, '101', '005', 'Saúde da Família para a População Ribeirinha-Saúde Bucal MI', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (249, 1, '103', '005', 'Unidade de Suporte Básico de vida: Equipe Embarcação', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (250, 1, '104', '005', 'Unidade de autorizações de TFD interestaduais', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (251, 1, '105', '005', 'Tratamento neurocirúrgico da dor funcional', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (252, 1, '106', '005', 'Unidade Dispensadora de Medicamentos - UDM', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (253, 1, '107', '005', 'Implante Coclear', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (254, 1, '109', '005', 'Atenção Básica à Adolescentes em Unidade Socioeducativa', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (255, 1, '112', '005', 'Centro de parto normal', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (256, 1, '113', '005', 'Equipe de cuidados domiciliares', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (257, 1, '114', '005', 'Cirurgia oral', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (258, 1, '165', '005', 'Serviço de Referência para Atenção Integral à Saúde de Pessoas Idosas em Situação de Violência Sexual', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (259, 1, '164', '006', 'Manutenção e Adaptação de OPM Auditiva', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (260, 1, '115', '006', 'UA Adulto', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (261, 1, '166', '006', 'Células, Tecidos e Órgãos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (262, 1, '139', '006', 'Acompanhamento a pacientes com diagnósticos de Deficiência Biotinidase', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (263, 1, '140', '006', 'Pronto Atendimento Clínico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (264, 1, '145', '006', 'Exames hormonais', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (265, 1, '148', '006', 'Acompanhamento pós-transplante de medula óssea', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (266, 1, '149', '006', 'Fígado', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (267, 1, '159', '006', 'Núcleo Ampliado de Saúde da Família e Atenção Primária', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (268, 1, '160', '006', 'TELECONSULTA', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (269, 1, '161', '006', 'TELECONSULTA', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (270, 1, '116', '006', 'Cardiologia Endovascular Extracardíaco', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (271, 1, '121', '006', 'Radiologia intervencionista', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (272, 1, '122', '006', 'Teste Holter por Telemedicina', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (273, 1, '125', '006', 'Farmácia Hospitalar', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (274, 1, '126', '006', 'Assistência fisioterapêutica em queimados', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (275, 1, '130', '006', 'Tratamento em DRC', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (276, 1, '131', '006', 'Projeto Olhar Brasil - Programa Saúde na Escola (PSE)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (277, 1, '134', '006', 'Termalismo/Crenoterapia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (278, 1, '101', '006', 'Saúde da Família Fluvial', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (279, 1, '103', '006', 'Veículos de intervenção rápida', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (280, 1, '104', '006', 'Central Estadual de Regulação da Alta Complexidade', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (281, 1, '105', '006', 'Investigação e cirurgia de epilepsia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (282, 1, '107', '006', 'Triagem Auditiva Neonatal', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (283, 1, '112', '006', 'Casa da Gestante, Bebê e Puérpera', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (284, 1, '114', '006', 'Cirurgia buco-maxilo-facial', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (285, 1, '165', '006', 'Serviço de referência para interrupção de gravidez nos casos previstos em LEI', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (286, 1, '164', '007', 'Dispensação de OPM Oftalmológica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (287, 1, '115', '007', 'UA Infantojuvenil', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (288, 1, '166', '007', 'Medicamentos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (289, 1, '140', '007', 'Pronto Atendimento Pediátrico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (290, 1, '145', '007', 'Exames de  vigilância epidemiológica e  ambiental', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (291, 1, '149', '007', 'Pâncreas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (292, 1, '159', '007', 'Atenção Primária para População Ribeirinha', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (293, 1, '160', '007', 'TELEMONITORAMENTO', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (294, 1, '116', '007', 'Cardiologia Clínica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (295, 1, '121', '007', 'Radiologia por telemedicina', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (296, 1, '122', '007', 'Exame Eletrocardiografico por Telemedicina', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (297, 1, '123', '007', 'OPM em odontologia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (298, 1, '125', '007', 'Farmácia Viva', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (299, 1, '126', '007', 'Assistência fisioterapêutica nas alterações em neurologia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (300, 1, '131', '007', 'Projeto Olhar Brasil - Programa Brasil Alfabetizado (PBA)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (301, 1, '134', '007', 'Antroposofia Aplicada à Saúde', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (302, 1, '135', '007', 'Oficina Ortopédica Fixa', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (303, 1, '101', '007', 'Saúde da Família Fluvial com Saúde Bucal', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (304, 1, '103', '007', 'Outros veículos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (305, 1, '104', '007', 'Regulação Nacional de Alta Complexidade', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (306, 1, '105', '007', 'Tratamento endovascular', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (307, 1, '112', '007', 'Atenção especializada ao seguimento do recém-nascido e crianças egressos de unidades neonatais (ANEO)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (308, 1, '114', '007', 'Atendimento à pessoa com deficiência', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (309, 1, '165', '007', 'Atenção Ambulatorial  ás Pessoas em Situação de Violência Sexual', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (310, 1, '164', '008', 'Adaptação de OPM Oftalmológica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (311, 1, '115', '008', 'Unidade de Atenção em Regime Residencial', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (312, 1, '166', '008', 'Saneantes Domissanitários', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (313, 1, '140', '008', 'Pronto Atendimento Obstétrico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (314, 1, '145', '008', 'Exames toxicológicos ou de monitorização terapêutica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (315, 1, '149', '008', 'Retirada de orgãos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (316, 1, '152', '008', 'Hospitalidade Indígena', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (317, 1, '159', '008', 'Consultório na Rua', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (318, 1, '160', '008', 'TELEORIENTACAO', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (319, 1, '116', '008', 'Serviço de Atenção Cardiovascular/Cardiologia Angiologia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (320, 1, '121', '008', 'Ultra-sonografia por telemedicina', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (321, 1, '122', '008', 'Exame Eletroencefalografico por Telemedicina', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (322, 1, '123', '008', 'OPM buco-maxilo-facial', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (323, 1, '126', '008', 'Diagnóstico cinético funcional', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (324, 1, '134', '008', 'Práticas Expressivas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (325, 1, '135', '008', 'Oficina Ortopédica Intinerante', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (326, 1, '101', '008', 'ESF Tipo I, II, III, IV ou Transitória', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (327, 1, '103', '008', 'Ambulância de resgate', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (328, 1, '104', '008', 'Regulação Ambulatorial de Média Complexidade', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (329, 1, '105', '008', 'Neurocirurgia funcional estereotáxica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (330, 1, '107', '008', 'Atenção Especializada às Pessoas com Deficiência Auditiva', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (331, 1, '112', '008', 'Atenção especializada gestação de alto risco (AGAR)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (332, 1, '165', '008', 'Coleta de  Vestígios de Violência Sexual', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (333, 1, '164', '009', 'Substitução/Troca de OPM', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (334, 1, '115', '009', 'Tratamento em Regime de Internação para Transtornos Mentais e Dependência Química', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (335, 1, '140', '009', 'Pronto Atendimento Psiquiátrico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (336, 1, '145', '009', 'Exames microbiológicos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (337, 1, '149', '009', 'Pele', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (338, 1, '152', '009', 'Gestão da Atenção e Saneamento à Populações Indígenas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (339, 1, '159', '009', 'Atenção Primária para População Prisional', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (340, 1, '160', '009', 'TELEINTERCONSULTA', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (341, 1, '121', '009', 'Tomografia computadorizada por telemedicina', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (342, 1, '122', '009', 'Exame Eletroneuromiografia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (343, 1, '134', '009', 'Ayurveda', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (344, 1, '135', '009', 'Oficina Ortopédica Intinerante Fluvial', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (345, 1, '101', '009', 'ESF Tipo I, II, III, IV ou Transitória com Saúde Bucal MI', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (346, 1, '104', '009', 'Regulação do Acesso a Ações e Serviços de Saúde', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (347, 1, '105', '009', 'Polissonografia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (348, 1, '166', '009', 'Produtos para a Saúde', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (349, 1, '103', '010', 'Motolância', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (350, 1, '123', '010', 'OPM em queimados', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (351, 1, '135', '010', 'Atenção Fonoaudiológica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (352, 1, '140', '010', 'Pronto Atendimento Oftalmológico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (353, 1, '160', '010', 'TELETRIAGEM', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (354, 1, '101', '010', 'ESF Tipo I, II, III, IV ou Transitória com Saúde Bucal MII', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (355, 1, '159', '010', 'Atenção Primária para Adolescentes em Unidade Socioeducativa', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (356, 1, '115', '010', 'DESINST de Pessoas com Transtorno  Mental em Conflito com a Lei', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (357, 1, '121', '010', 'Ressonância magnética por telemedicina', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (358, 1, '166', '010', 'Cosméticos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (359, 1, '152', '010', 'Saúde Bucal à Populações Indígenas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (360, 1, '149', '010', 'Válvulas cardíacas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (361, 1, '122', '010', 'Exame videoeletroencefalografia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (362, 1, '164', '010', 'Dispensação de OPM em Gastroenterologia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (363, 1, '145', '010', 'Exames em outros líquidos biológicos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (364, 1, '134', '010', 'Práticas Naturais', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (365, 1, '134', '011', 'Práticas Manuais', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (366, 1, '123', '011', 'OPM em nefrologia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (367, 1, '122', '011', 'Potenciais Evocados', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (368, 1, '121', '011', 'Radiologia intervencionista por telemedicina', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (369, 1, '103', '011', 'Unidade de Suporte Avançado de vida: Equipe Embarcação', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (370, 1, '101', '011', 'ESF Transitória', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (371, 1, '166', '011', 'Desinfestantes', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (372, 1, '164', '011', 'Dispensação de OPM em Urologia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (373, 1, '160', '011', 'TELERREGULACAO', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (374, 1, '149', '011', 'Osteocondroligamentos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (375, 1, '145', '011', 'Exames de genética', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (376, 1, '140', '011', 'Pronto Atendimento Odontológico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (377, 1, '135', '011', 'Atenção Fisioterapeutica', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (378, 1, '164', '012', 'Confecção de OPM Auxiliares de Locomoção e Ortopédicas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (379, 1, '134', '012', 'Práticas Psicodinâmicas', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (380, 1, '140', '012', 'Pronto Socorro Pediátrico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (381, 1, '135', '012', 'Atenção à Saúde das Pessoas Ostomizadas I', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (382, 1, '145', '012', 'Exames para triagem neonatal', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (383, 1, '103', '012', 'Equipe Aeromédico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (384, 1, '101', '012', 'Saúde da Família para a População Ribeirinha - Saúde Bucal MII', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (385, 1, '166', '012', 'Imunobiológicos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (386, 1, '149', '012', 'Separação, avaliação biomicroscópica e conservação da córnea/esclera', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (387, 1, '122', '012', 'Potenciais Evocados por Telemedicina', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (388, 1, '121', '012', 'Mamografia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (389, 1, '123', '012', 'OPM - Projeto Olhar Brasil', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (390, 1, '134', '013', 'Ozônioterapia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (391, 1, '123', '013', 'OPM Projeto Olhar Brasil - Programa Saúde na Escola (PSE)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (392, 1, '166', '013', 'Insumos Farmacêuticos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (393, 1, '135', '013', 'Atenção à Saúde das Pessoas Ostomizadas II', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (394, 1, '101', '013', 'ESB MI', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (395, 1, '149', '013', 'Contagem endotelial corneana', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (396, 1, '121', '013', 'Mamografia por Telemedicina', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (397, 1, '145', '013', 'Exames imunohematológicos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (398, 1, '140', '013', 'Pronto Socorro Obstétrico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (399, 1, '101', '014', 'ESB MII', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (400, 1, '123', '014', 'OPM Projeto Olhar Brasil - Programa Brasil Alfabetizado (PBA)', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (401, 1, '134', '014', 'Aromaterapia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (402, 1, '140', '014', 'Pronto Socorro Cardiovascular', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (403, 1, '149', '014', 'Acompanhamento de paciente transplantado', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (404, 1, '166', '014', 'Material Biológico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (405, 1, '166', '015', 'Sangue e Hemoderivados', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (406, 1, '140', '015', 'Pronto Socorro Neurologia/Neurocirurgia', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (407, 1, '149', '015', 'Ações para doação e captação de órgãos e tecidos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (408, 1, '134', '015', 'Imposição de Mãos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (409, 1, '149', '016', 'Retirada de globo ocular humano para transplante', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (410, 1, '166', '016', 'Surtos de Toxinfecção', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (411, 1, '140', '016', 'Pronto Socorro Traumato-Ortopédico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (412, 1, '166', '017', 'Diversos', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (413, 1, '140', '017', 'Pronto Socorro Odontológico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (414, 1, '140', '018', 'Pronto Socorro Oftalmológico', '202504');
INSERT INTO tb_servico_classificacao (id, version_id, co_servico, co_classificacao, no_classificacao, dt_competencia) VALUES (415, 1, '140', '019', 'Pronto Socorro Geral/Clínico', '202504');
