-- Script SQL INSERT para a tabela: tb_sub_grupo
-- Gerado a partir do arquivo de dados: tb_sub_grupo.txt (Encoding Leitura: latin-1)
-- Usando version_id: 1
-- Data de geração: 2025-05-12 21:55:55

INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (1, 1, '02', '01', 'Coleta de material', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (2, 1, '04', '01', 'Pequenas cirurgias e cirurgias de pele, tecido subcutâneo e mucosa', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (3, 1, '05', '01', 'Coleta e exames para fins de doação de orgãos, tecidos e células e de transplante', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (4, 1, '01', '01', 'Ações coletivas/individuais em saúde', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (5, 1, '06', '01', 'Medicamentos de dispensação excepcional', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (6, 1, '07', '01', 'Órteses, próteses e materiais especiais não relacionados ao ato cirúrgico', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (7, 1, '03', '01', 'Consultas / Atendimentos / Acompanhamentos', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (8, 1, '09', '01', 'Atenção em Oncologia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (9, 1, '08', '01', 'Ações relacionadas ao estabelecimento', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (10, 1, '04', '02', 'Cirurgia de glândulas endócrinas', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (11, 1, '03', '02', 'Fisioterapia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (12, 1, '02', '02', 'Diagnóstico em laboratório clínico', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (13, 1, '01', '02', 'Vigilância em saúde', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (14, 1, '09', '02', 'Atenção em Cardiologia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (15, 1, '08', '02', 'Ações relacionadas ao atendimento', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (16, 1, '07', '02', 'Órteses, próteses e materiais especiais relacionados ao ato cirúrgico', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (17, 1, '06', '02', 'Medicamentos estratégicos', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (18, 1, '05', '02', 'Avaliação de morte encefálica', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (19, 1, '03', '03', 'Tratamentos clínicos (outras especialidades)', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (20, 1, '02', '03', 'Diagnóstico por anatomia patológica e citopatologia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (21, 1, '08', '03', 'Autorização / regulação', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (22, 1, '05', '03', 'Ações relacionadas à doação de orgãos e tecidos para transplante', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (23, 1, '09', '03', 'Atenção em Ortopedia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (24, 1, '04', '03', 'Cirurgia do sistema nervoso central e periférico', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (25, 1, '06', '03', 'Medicamentos de âmbito hospitalar e urgência', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (26, 1, '04', '04', 'Cirurgia das vias aéreas superiores, da face, da cabeça e do pescoço', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (27, 1, '03', '04', 'Tratamento em oncologia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (28, 1, '09', '04', 'Atenção em Otorrinolaringologia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (29, 1, '02', '04', 'Diagnóstico por radiologia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (30, 1, '06', '04', 'Componente especializado da assistência farmacêutica', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (31, 1, '05', '04', 'Processamento de tecidos para transplante', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (32, 1, '08', '04', 'Telessaúde', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (33, 1, '02', '05', 'Diagnóstico por ultrasonografia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (34, 1, '03', '05', 'Tratamento em nefrologia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (35, 1, '04', '05', 'Cirurgia do aparelho da visão', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (36, 1, '05', '05', 'Transplante de orgãos, tecidos e células', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (37, 1, '09', '05', 'Atenção em Oftalmologia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (38, 1, '02', '06', 'Diagnóstico por tomografia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (39, 1, '04', '06', 'Cirurgia do aparelho circulatório', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (40, 1, '05', '06', 'Acompanhamento e intercorrências no pré e pós-transplante', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (41, 1, '03', '06', 'Hemoterapia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (42, 1, '04', '07', 'Cirurgia do aparelho digestivo, orgãos anexos e parede abdominal', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (43, 1, '02', '07', 'Diagnóstico por ressonância magnética', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (44, 1, '03', '07', 'Tratamentos odontológicos', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (45, 1, '03', '08', 'Tratamento de lesões, envenenamentos e outros, decorrentes de causas externas', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (46, 1, '02', '08', 'Diagnóstico por medicina nuclear in vivo', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (47, 1, '04', '08', 'Cirurgia do sistema osteomuscular', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (48, 1, '03', '09', 'Terapias especializadas', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (49, 1, '02', '09', 'Diagnóstico por endoscopia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (50, 1, '04', '09', 'Cirurgia do aparelho geniturinário', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (51, 1, '04', '10', 'Cirurgia de mama', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (52, 1, '02', '10', 'Diagnóstico por radiologia intervencionista', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (53, 1, '03', '10', 'Parto e nascimento', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (54, 1, '02', '11', 'Métodos diagnósticos em especialidades', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (55, 1, '03', '11', 'Cuidados Paliativos', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (56, 1, '04', '11', 'Cirurgia obstétrica', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (57, 1, '02', '12', 'Diagnóstico e procedimentos especiais em hemoterapia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (58, 1, '04', '12', 'Cirurgia torácica', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (59, 1, '02', '13', 'Diagnóstico em vigilância epidemiológica e ambiental', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (60, 1, '04', '13', 'Cirurgia reparadora', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (61, 1, '02', '14', 'Diagnóstico por teste rápido', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (62, 1, '04', '14', 'Bucomaxilofacial', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (63, 1, '04', '15', 'Outras cirurgias', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (64, 1, '04', '16', 'Cirurgia em oncologia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (65, 1, '04', '17', 'Anestesiologia', '202504');
INSERT INTO tb_sub_grupo (id, version_id, co_grupo, co_sub_grupo, no_sub_grupo, dt_competencia) VALUES (66, 1, '04', '18', 'Cirurgia em nefrologia', '202504');
