-- Script SQL INSERT para a tabela: tb_grupo_habilitacao
-- Gerado a partir do arquivo de dados: tb_grupo_habilitacao.txt (Encoding Leitura: latin-1)
-- Usando version_id: 1
-- Data de geração: 2025-05-12 21:55:55

INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (1, 1, '0176', 'h', 'h');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (2, 1, '0178', '2409 e 2430', 'Grupo do transplante de figado');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (3, 1, '0177', '0801 e 0803d', 'dsa');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (4, 1, '0174', 'Teste', 'Criando um grupo para teste');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (5, 1, '0175', 'Teste', 'Criando um Grupo para Teste');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (6, 1, '0173', '2418 e 2425', 'Exames de histocompatibilidade através de sorologia e ou biologia molecular - Tipo II e Cadastramento de doadores voluntários de medula óssea e outros precursores hematopoéticos');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (7, 1, '0001', '0801 e 0803', 'Unidade de Assistência de Alta Complexidade Cardiovascular com Cirurgia Cardiovascular e Procedimentos em Cardiologia Intervencionista');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (8, 1, '0002', '0801 e 0804', 'Unidade de Assistência de Alta Complexidade Cardiovascular com Cirurgia Cardiovascular Pediátrica');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (9, 1, '0003', '0801 e 0805', 'Unidade de Assistência de Alta Complexidade Cardiovascular com Cirurgia Vascular');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (10, 1, '0004', '0801 e 0806', 'Unidade de Assistência de Alta Complexidade Cardiovascular com Cirurgia Vascular e Procedimentos Endovasculares Extracardíacos');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (11, 1, '0005', '0801 e 0807', 'Unidade de Assistência de Alta Complexidade Cardiovascular com Laboratório de Eletrofisiologia, Cirurgia Cardiovascular e procedimentos de Cardiologia Intervencionista');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (12, 1, '0006', '0802 e 0803', 'Centro de Referência em Alta Complexidade Cardiovascular com Cirurgia Cardiovascular e Procedimentos em Cardiologia Intervencionista');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (13, 1, '0007', '0802 e 0804', 'Centro de Referência em Alta Complexidade Cardiovascular com Cirurgia Cardiovascular Pediátrica');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (14, 1, '0008', '0802 e 0805', 'Centro de Referência em Alta Complexidade Cardiovascular com Cirurgia Vascular');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (15, 1, '0009', '0802 e 0806', 'Centro de Referência em Alta Complexidade Cardiovascular com Cirurgia Vascular e Procedimentos Endovasculares Extracardíacos');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (16, 1, '0010', '0802 e 0807', 'Centro de Referência em Alta Complexidade Cardiovascular com Laboratório de Eletrofisiologia, Cirurgia Cardiovascular e procedimentos de Cardiologia Intervencionista');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (17, 1, '0051', '2301 e 2303', 'Unidade de assitência de alta complexidade em terapia nutricional e Enteral');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (18, 1, '0071', '2301 e 2304', 'Unidade de assistencia de alta complexidade em terapia nutricional e Enteral e parenteral');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (19, 1, '0072', '2301 e 2305', 'Unidade de assistencia de alta complexidade em terapia nutricional e Enteral e parenteral com manipulação e fabricação de formula nutricional');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (20, 1, '0073', '2302 e 2303', 'Centro de referência de alta complexidade em terapia nutricional e Enteral');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (21, 1, '0074', '2302 e 2304', 'Centro de referência de alta complexidade em terapia nutricional e Enteral e parenteral');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (22, 1, '0091', '2302 e 2305', 'Centro de referência de alta complexidade em terapia nutricional e Enteral e parenteral com manipulação de formula nutricional');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (23, 1, '0151', '1601-1603-1604-1605', 'Assistência em Neurologia');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (24, 1, '0181', '1708 e 1722', 'UNACON');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (25, 1, '0184', '1709 e 1722', 'CACON');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (26, 1, '0179', '1706 e 1722', 'UNACON');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (27, 1, '0180', '1707 e 1722', 'UNACON');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (28, 1, '0182', '1712 e 1722', 'UNACON');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (29, 1, '0183', '1713 e 1722', 'UNACON');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (30, 1, '0185', '0801, 0803 e 0815', 'Cardiologia');
INSERT INTO tb_grupo_habilitacao (id, version_id, nu_grupo_habilitacao, no_grupo_habilitacao, ds_grupo_habilitacao) VALUES (31, 1, '0186', '0802, 0803 e 0815', 'Cardiologia');
