-- Script SQL INSERT para a tabela: tb_descricao_detalhe
-- Gerado a partir do arquivo de dados: tb_descricao_detalhe.txt (Encoding Leitura: latin-1)
-- Usando version_id: 1
-- Data de geração: 2025-05-12 21:55:55

INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (1, 1, '001', 'DESTINA-SE A IDENTIFICAR SE NO VALOR DO PROCEDIMENTO JÁ ESTÁ INCLUSO QUALQUER TIPO DE ANESTESIA, EXCETO ANESTESIA LOCAL, POIS ESTA JÁ ESTÁ INCLUSA NO VALOR DO PROCEDIMENTO. ||NOS PROCEDIMENTOS HOSPITALARES COM O ATRIBUTO "INCLUI ANESTESIA" SIGNIFICA QUE O VALOR DA ANESTESIA ESTÁ INCLUÍDO NO COMPONENTE SP (SERVIÇOS PROFISSIONAIS), NÃO PERMITINDO O REGISTRO DE CÓDIGOS DE ANESTESIA EM SEPARADO, DO PROCEDIMENTO PRINCIPAL. NOS PROCEDIMENTOS AMBULATORIAIS, COM O ATRIBUTO "INCLUI ANESTESIA" SIGNIFICA QUE O VALOR DA ANESTESIA ESTÁ INCLUÍDO NO COMPONENTE SA (SERVIÇO AMBULATORIAL). ||', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (2, 1, '003', 'IDENTIFICA OS PROCEDIMENTOS QUE PERMITEM O REGISTRO NA AIH DE CONTINUIDADE, OU SEJA, LONGA PERMANÊNCIA.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (3, 1, '004', 'INDICA QUE PELAS CARACTERÍSTICAS PRÓPRIAS DO PROCEDIMENTO OU PELA CONDIÇÃO CLÍNICA DO PACIENTE ADMITE DIAS DE PERMANÊNCIA ALÉM DO DOBRO DOS DIAS PREVISTOS NO ATRIBUTO -"MÉDIA DE PERMANÊNCIA". NESSE CASO É NECESSÁRIO O REGISTRO NA AIH DO CÓDIGO DE PROCEDIMENTO 08.02.01.019-9.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (4, 1, '005', 'IDENTIFICA OS PROCEDIMENTOS QUE ADMITEM LIBERAÇÃO PELO GESTOR DE SAÚDE LOCAL, DE QUANTIDADE SUPERIOR A DEFINIDA EM SEU ATRIBUTO QUANTIDADE MÁXIMA.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (5, 1, '006', 'IDENTIFICA OS PROCEDIMENTOS QUE INTEGRAM A POLÍTICA NACIONAL DE REGULAÇÃO DE ALTA COMPLEXIDADE, INSTITUÍDOS EM PORTARIAS ESPECÍFICAS.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (6, 1, '007', 'PROCEDIMENTOS CUJO VALOR É FIXADO POR DIA DE INTERNAÇÃO E, PORTANTO, NÃO TÊM MÉDIA DE PERMANÊNCIA DEFINIDA E SIM NÚMERO MÁXIMO DE DIAS DE INTERNAÇÃO A SEREM REGISTRADAS NA AIH.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (7, 1, '008', 'IDENTIFICA OS PROCEDIMENTOS PRINCIPAIS QUE POR CARACTERÍSTICAS DO ATENDIMENTO NÃO É PERMITIDO ALTERAR O PROCEDIMENTO PRINCIPAL SOLICITADO/AUTORIZADO NO LAUDO.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (8, 1, '009', 'Identifica os procedimentos que exigem identificação do usuário pelo Cadastro de Pessoa Física (CPF), preferencialmente, ou pelo Cartão Nacional de Saúde (CNS).', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (9, 1, '011', 'IDENTIFICA OS PROCEDIMENTOS PARA OS QUAIS O PACIENTE PODE RECEBER ALTA HOSPITALAR DIRETAMENTE DO LEITO DA UTI, NÃO SENDO EXIGIDA A SUA PERMANÊNCIA EM LEITO DE ENFERMARIA APÓS A ALTA DA UTI.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (10, 1, '012', 'IDENTIFICA OS PROCEDIMENTOS QUE EXIGEM O REGISTRO DA IDADE DOS USUÁRIOS ATENDIDOS.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (11, 1, '013', 'IDENTIFICA OS PROCEDIMENTOS PARA OS QUAIS DEVE SER VERIFICADA, NO CNES, A EXISTÊNCIA DE HABILITAÇÃO DO ESTABELECIMENTO TERCEIRIZADO.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (12, 1, '014', 'IDENTIFICA OS PROCEDIMENTOS DE TRATAMENTO CONTÍNUO PERMITIDOS EM APAC DE CONTINUIDADE.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (13, 1, '015', 'IDENTIFICA OS PROCEDIMENTOS QUE PODERÃO SER INFORMADOS APENAS PELOS ESTABELECIMENTOS DE SAÚDE IDENTIFICADOS NO CNES COMO SENDO DO TIPO HOSPITAL ESPECIALIZADO COM SUBTIPO DE ESTABELECIMENTO EM PSIQUIATRIA (07.06).', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (14, 1, '017', 'IDENTIFICA OS PROCEDIMENTOS QUE NÃO PODEM SER REALIZADOS SEM O REGISTRO DE OPM.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (15, 1, '020', 'IDENTIFICA, PARA FINS DE MONITORAMENTO, OS PROCEDIMENTOS QUE INTEGRAM O ROL DE PROCEDIMENTOS PASSÍVEIS DE SEREM REALIZADOS NO CENTRO DE ESPECIALIDADE ODONTOLÓGICA, DEFINIDOS EM PORTARIA ESPECÍFICA.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (16, 1, '021', 'IDENTIFICA OS PROCEDIMENTOS QUE NÃO EXIGEM A INFORMAÇÃO DE CBO.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (17, 1, '022', 'Identifica os procedimentos na APAC que exigem preenchimento de dados complementares.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (18, 1, '023', 'Identifica os procedimentos em que o registro é efetuado exclusivamente no SISCOLO.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (19, 1, '024', 'Identifica os procedimentos em que o registro é efetuado exclusivamente no SISPRENATAL.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (20, 1, '025', 'Identifica os procedimentos em que o registro é efetuado exclusivamente no SISMAMA.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (21, 1, '026', 'Identifica o procedimento que exige registro de procedimentos secundários compativeis.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (22, 1, '029', 'Procedimentos que admitem a apresentação de até cinco competências anteriores.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (23, 1, '033', 'Identifica que a validade da APAC é fixada em 03 competencias. Em caso de necessidade de fechar na primeira competencia, terá que ser fechado em definitivo.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (24, 1, '034', 'Identifica os procedimentos que não exigem identificação do usuário pelo Cadastro de Pessoa Física (CPF) ou pelo Cartão Nacional de Saúde (CNS);', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (25, 1, '036', 'Identifica que o procediemnto que tem o Instrumento de Registro RASS, exige autorização.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (26, 1, '037', 'Identifica que é necessário a informação do fornecedor para os referidos procediementos.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (27, 1, '038', 'Exige preenchimento dos campos serviço/classificação no momento do registro do procedimento.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (28, 1, '040', 'Identifica os procedimentos em que o registro é efetuado obrigatoriamente no SISCAN.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (29, 1, '041', 'Identifica que a validade da APAC é fixada em 12 competencias. Em caso de necessidade de fechar na primeira competencia, terá que ser fechado em definitivo.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (30, 1, '042', 'PROCEDIMENTOS QUE ESTIVEREM MARCADOS COM ESTE ATRIBUTO NÃO PODERÃO SER LIBERADOS DESTA CRÍTICA PELO GESTOR.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (31, 1, '043', 'ESTE ATRIBUTO INDICA QUE, AO REGISTRAR O PROCEDIMENTO, É OBRIGATÓRIO INFORMAR OS CID DE CAUSAS ASSOCIADAS.||||', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (32, 1, '044', 'PROCEDIMENTOS CIRÚRGICOS ELETIVOS DE MÉDIA COMPLEXIDADE REDEFINIDOS PELA PORTARIA/GM N° 1.294, DE 25 DE MAIO DE 2017.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (33, 1, '045', 'Diárias de leitos complementares	São leitos de internação destinados a pacientes que necessitam de assistência especializada exigindo características especiais, tais como: as unidades de isolamento reverso e as unidades de Tratamento intensiva e semi-intensiva. Este atributo foi inserido para atender ao CMD.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (34, 1, '046', 'Atributo criado para atender ao CMD. Só serão vinculados aos procedimentos quando passar a valer no RTS.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (35, 1, '047', 'Atributo inserido para atender ao CMD. Os procedimentos só serão vinculados quando estiver funcionando no RTS.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (36, 1, '048', 'Obrigatório registro de CID.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (37, 1, '049', 'Permite registrar equipe Cirúrgica.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (38, 1, '050', 'Atributo que identifica o registro do número do Cartão Nacional de Saúde do recém-nascido no Conjunto Mínimo de Dados-CMD.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (39, 1, '051', 'Organizar e ampliar o acesso para redução das filas para procedimentos Cirúrgicos da Atenção Especializada (Eletivos).', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (40, 1, '052', 'Para o programa das Eletiva', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (41, 1, '053', 'Programa Mais Acesso a Especialistas (PMAE): Identifica os procedimentos integrantes do PMAE, que objetiva a qualificação e a ampliação do acesso a consultas, exames e outros procedimentos diagnósticos e terapêuticos na Atenção Ambulatorial Especializada à Saúde.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (42, 1, '054', 'Identifica que a validade da APAC é de, no máximo, 02 competências e não admite APAC de continuidade.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (43, 1, '055', 'Identifica os procedimentos que exigem a informação de data do diagnóstico de Neoplasia.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (44, 1, '056', 'Determina que deverá ser executado e registrado na APAC pelo menos um procedimento do subgrupo 02.06 - Diagnóstico por tomografia da Tabela de Procedimentos do SUS, respeitando as compatibilidades estabelecidas entre procedimento principal e secundários.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (45, 1, '057', 'Determina que seja executado e registrado na APAC pelo menos um procedimento do subgrupo 02.07 - Diagnóstico por ressonância magnética da Tabela de Procedimentos do SUS, respeitando as compatibilidades estabelecidas entre procedimento principal e secundários.', '202504');
INSERT INTO tb_descricao_detalhe (id, version_id, co_detalhe, ds_detalhe, dt_competencia) VALUES (46, 1, '058', 'Determina que a identificação do usuário atendido seja realizada por meio do CPF. Excetuam-se a este regramento a população indígena, a qual poderá ser identificada por meio do Cartão Nacional de Saúde (CNS).', '202504');
