-- Script SQL INSERT para a tabela: tb_habilitacao
-- Gerado a partir do arquivo de dados: tb_habilitacao.txt (Encoding Leitura: latin-1)
-- Usando version_id: 1
-- Data de geração: 2025-05-12 21:55:55

INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (1, 1, '0101', 'Centro de referência em atenção a saúde do idoso', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (2, 1, '0202', 'Unidade de alta complexidade ao paciente portador de obesidade grave', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (3, 1, '0203', 'Assistência em Alta Complexidade ao individuo com Obesidade', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (4, 1, '0301', 'Centros/Núcleos para realização de implante coclear', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (5, 1, '0305', 'Atenção Especializada às Pessoas com Deficiência Auditiva', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (6, 1, '0401', 'Centro de tratamento da má formação labio-palatal', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (7, 1, '0403', 'Centro de Especialidade Odontológica - CEO Tipo I', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (8, 1, '0404', 'Centro de Especialidade Odontológica - CEO Tipo II', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (9, 1, '0405', 'Centro de Especialidade Odontológica - CEO Tipo III', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (10, 1, '0406', 'Serviço de Especialidade em Saúde Bucal', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (11, 1, '0503', 'Unidade de Atenção Especializada em Oftalmologia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (12, 1, '0504', 'Centro de Referência em Oftalmologia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (13, 1, '0505', 'Projeto Olhar Brasil', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (14, 1, '0506', 'Tratamento do Glaucoma com medicamentos no âmbito da Política Nacional de Atenção Oftalmológica', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (15, 1, '0507', 'Consultório Itinerante de Ensino em Oftalmologia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (16, 1, '0508', 'Tratamento do Glaucoma com medicamentos do Componente Especializado da Assistência Farmacêutica', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (17, 1, '0601', 'Psiquiatria - Classe I', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (18, 1, '0602', 'Psiquiatria - Classe II', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (19, 1, '0603', 'Psiquiatria - Classe III', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (20, 1, '0604', 'Psiquiatria - Classe IV', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (21, 1, '0605', 'Psiquiatria - Classe V', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (22, 1, '0606', 'Psiquiatria - Classe VI', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (23, 1, '0607', 'Psiquiatria - Classe VII', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (24, 1, '0608', 'Psiquiatria - Classe VIII', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (25, 1, '0609', 'Psiquiatria - Classe IX', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (26, 1, '0610', 'Psiquiatria - Classe X', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (27, 1, '0611', 'Psiquiatria - Classe XI', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (28, 1, '0612', 'Psiquiatria - Classe XII', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (29, 1, '0613', 'Psiquiatria - Classe XIII', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (30, 1, '0614', 'Psiquiatria - Classe XIV', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (31, 1, '0615', 'PNASS maior que 80%', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (32, 1, '0616', 'Centro de Atenção Psicossocial - CAPS I', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (33, 1, '0617', 'Centro de Atenção Psicossocial - CAPS II', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (34, 1, '0618', 'Centro de Atenção Psicossocial - CAPS III', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (35, 1, '0619', 'Centro de Atenção Psicossocial Álcool e Drogas - CAPSad', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (36, 1, '0620', 'Centro de Atenção Psicossocial Infantil - CAPSi', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (37, 1, '0621', 'Serviço hospitalar de referência para a atenção integral aos usuários de álcool e outras drogas', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (38, 1, '0622', 'Psiquiatria Classe I - PT/GM nº251/02', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (39, 1, '0623', 'Psiquiatria Classe II - PT/GM nº251/02', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (40, 1, '0624', 'Psiquiatria Classe III - PT/GM nº251/02', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (41, 1, '0625', 'Psiquiatria Classe IV - PT/GM nº 251/02', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (42, 1, '0626', 'Psiquiatria Classe V - PT/GM nº251/02', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (43, 1, '0627', 'Psiquiatria Classe VI - PT/GM nº251/02', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (44, 1, '0628', 'Psiquiatria Classe VII - PT/GM nº251/02', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (45, 1, '0629', 'Psiquiatria Classe VIII - PT/GM nº251/02', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (46, 1, '0630', 'Psiquiatria III', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (47, 1, '0631', 'Nível I', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (48, 1, '0632', 'Nível II', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (49, 1, '0633', 'Nível III', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (50, 1, '0634', 'Nível IV', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (51, 1, '0635', 'Centro de Atenção Psicossocial Álcool e Drogas - CAPS AD III', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (52, 1, '0636', 'Atenção a pessoas com sofrimento ou transtorno mental decorrente de alcool e outras drogas.', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (53, 1, '0637', 'CAPS AD IV', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (54, 1, '0801', 'Unidade de assistência de alta complexidade cardiovascular', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (55, 1, '0802', 'Centro de referência em alta complexidade cardiovascular', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (56, 1, '0803', 'Cirurgia cardiovascular e procedimentos em cardiologia intervencionista', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (57, 1, '0804', 'Cirurgia cardiovascular pediátrica', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (58, 1, '0805', 'Cirurgia vascular', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (59, 1, '0806', 'Cirurgia vascular e procedimentos endovasculares extracardíacos', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (60, 1, '0807', 'Laboratório de eletrofisiologia, cirurgia cardiovascular e procedimentos de cardiologia intervencionista', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (61, 1, '0808', 'Implante de marcapasso definitivo', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (62, 1, '0809', 'Cirurgia cardíaca', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (63, 1, '0810', 'Laboratório eletrofisiológico e terapia intervencionista', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (64, 1, '0811', 'QualiSUS Cardio Nível A', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (65, 1, '0812', 'QualiSUS Cardio Nível B', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (66, 1, '0813', 'QualiSUS Cardio Nível C', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (67, 1, '0814', 'QualiSUS Cardio Nível D', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (68, 1, '0815', 'Implante Percutâneo de Válvula Aórtica (TAVI)', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (69, 1, '0901', 'Cuidados prolongados - enfermidades cardiovasculares', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (70, 1, '0902', 'Cuidados prolongados - enfermidades pneumológicas', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (71, 1, '0903', 'Cuidados prolongados - enfermidades neurológicas', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (72, 1, '0904', 'Cuidados prolongados - enfermidades osteomuscular e do tecido conjuntivo', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (73, 1, '0905', 'Cuidados prolongados - enfermidades oncológicas', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (74, 1, '0906', 'Cuidados prolongados - enfermidades decorrentes da AIDS', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (75, 1, '0907', 'Cuidados prolongados - enfermidades devido a causas externas', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (76, 1, '1001', 'Centro de referência no tratamento da dor crônica', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (77, 1, '1101', 'Serviço hospitalar para tratamento AIDS', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (78, 1, '1102', 'Laboratório Especializado em Contagem de Linfócitos T CD4+/CD8+ e HIV1 Quant. do RNA', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (79, 1, '1103', 'Tratamento da lipoatrofia facial do portador de HIV/AIDS', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (80, 1, '1104', 'Tratamento da liopodistrofia do Portador de HIV/AIDS', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (81, 1, '1105', 'Laboratório Especializado em Contagem de Linfócitos T CD4+/CD8+', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (82, 1, '1106', 'Laboratório Especializado em Quantificação do RNA do HIV1', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (83, 1, '1201', 'Fibrose cística - Hospital Dia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (84, 1, '1202', 'Hospital Dia - Procedimentos cirúrgicos, diagnósticos ou terapêuticos', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (85, 1, '1203', 'Hospital Dia - AIDS', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (86, 1, '1204', 'Hospital Dia em intercorrências pós-transplante de medula óssea e de outros precursores hematopoéticos', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (87, 1, '1205', 'Hospital Dia - Geriatria', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (88, 1, '1206', 'Hospital Dia - Saúde Mental', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (89, 1, '1301', 'Internação domiciliar', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (90, 1, '1401', 'Referência hospitalar em atendimento secundário a gestante de alto risco', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (91, 1, '1402', 'Referência hospitalar em atendimento terciário a gestante de alto risco', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (92, 1, '1403', 'Unidade que realiza assistência ao parto sem distócia por enfermeiro obstetra ou obstetriz', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (93, 1, '1404', 'Hospital Amigo da Criança', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (94, 1, '1405', 'Centro de referência em triagem neonatal/acompanhamento e tratamento de doenças congênitas - fenilcetonuria/hipotireoidismo congenito', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (95, 1, '1406', 'Centro de referência em triagem neonatal/acompanhamento e tratamento - doenças falciformes e outras hemoglobinopatias', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (96, 1, '1407', 'Centro de referência em triagem neonatal/acompanhamento e tratamento - fibrose cística', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (97, 1, '1408', 'Referência em Triagem Neonatal Etapa I', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (98, 1, '1409', 'Diagnóse de Fibrose Cistica', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (99, 1, '1410', 'Unidade de Centro de Parto Normal Intra-Hospitalar Tipo I 3 PPP', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (100, 1, '1411', 'Unidade de Centro de Parto Normal Intra-Hospitalar Tipo I 5 PPP', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (101, 1, '1412', 'Unidade de Centro de Parto Normal Peri-Hospitalar 5 PPP', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (102, 1, '1413', 'Atenção Hospitalar de Referência à Gestação de Alto Risco Tipo 1', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (103, 1, '1414', 'Atenção Hospitalar de Referência à Gestação de Alto Risco Tipo 2', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (104, 1, '1415', 'Casa da Gestante, Bebê e Puérpera', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (105, 1, '1416', 'Hospital Amigo da Criança', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (106, 1, '1417', 'Unidade de Centro de Parto Normal Peri-Hospitalar 3 PPP', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (107, 1, '1418', 'Unidade de Centro de Parto Normal Intra-Hospitalar Tipo II 3 PPP', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (108, 1, '1419', 'Unidade de Centro de Parto Normal Intra-Hospitalar Tipo II 5 PPP', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (109, 1, '1501', 'Unidade de assistência de alta complexidade em nefrologia (serviço de nefrologia)', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (110, 1, '1502', 'Centro de referência de alta complexidade em nefrologia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (111, 1, '1504', 'Atenção Especializada em DRC com Hemodiálise', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (112, 1, '1505', 'Atenção Especializada em DRC com Diálise Peritoneal', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (113, 1, '1506', 'Atenção Especializada em DRC nos estágios 4 e 5-PréDialitico', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (114, 1, '1507', 'Unidade Especializada em DRC com TRS/Diálise Tipo I com Hemodiálise', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (115, 1, '1508', 'Unidade Especializada em DRC com TRS/Diálise Tipo I com Diálise Peritoneal', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (116, 1, '1509', 'Unidade Especializada em DRC com TRS/Diálise Tipo II com Hemodiálise', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (117, 1, '1510', 'Unidade Especializada em DRC com TRS/Diálise Tipo II com Diálise Peritoneal', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (118, 1, '1511', 'Unidade Especializada em DRC com TRS/Diálise Tipo III com Hemodiálise', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (119, 1, '1512', 'Unidade Especializada em DRC com TRS/Diálise Tipo III com Diálise Peritoneal', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (120, 1, '1513', 'Unidade Especializada em DRC com TRS/Diálise Tipo IV com Hemodiálise', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (121, 1, '1514', 'Unidade Especializada em DRC com TRS/Diálise Tipo IV com Diálise Peritoneal', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (122, 1, '1601', 'Unidade de assistência de alta complexidade em neurologia/neurocirurgia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (123, 1, '1602', 'Centro de referência de alta complexidade em neurologia/neurocirurgia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (124, 1, '1603', 'Trauma e anomalias do desenvolvimento', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (125, 1, '1604', 'Coluna e dos nervos periféricos', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (126, 1, '1605', 'Tumores do sistema nervoso', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (127, 1, '1606', 'Neurocirurgia vascular', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (128, 1, '1607', 'Tratamento neurocirúrgico da dor e funcional', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (129, 1, '1608', 'Investigação e cirurgia de epilepsia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (130, 1, '1609', 'Tratamento neuro-endovascular', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (131, 1, '1610', 'Neurocirurgia funcional esteriotáxica', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (132, 1, '1611', 'Epilepsia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (133, 1, '1612', 'Neurocirurgia I', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (134, 1, '1613', 'Neurocirurgia II', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (135, 1, '1614', 'Neurocirurgia III', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (136, 1, '1615', 'Centro de Atendimento de Urgência Tipo I aos Pacientes com AVC', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (137, 1, '1616', 'Centro de Atendimento de Urgência Tipo II aos Pacientes com AVC', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (138, 1, '1617', 'Centro de Atendimento de Urgência Tipo III aos Pacientes com AVC', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (139, 1, '1618', 'Neurocirurgia Endovascular/Trombectomia Mecanica', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (140, 1, '1704', 'Serviço isolado de radioterapia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (141, 1, '1705', 'Serviço isolado de quimioterapia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (142, 1, '1706', 'UNACON', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (143, 1, '1707', 'UNACON com serviço de radioterapia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (144, 1, '1708', 'UNACON com serviço de hematologia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (145, 1, '1709', 'UNACON com serviço de oncologia pediátrica', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (146, 1, '1710', 'UNACON exclusiva de hematologia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (147, 1, '1711', 'UNACON exclusiva de oncologia pediátrica', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (148, 1, '1712', 'CACON', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (149, 1, '1713', 'CACON com serviço de oncologia pediátrica', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (150, 1, '1714', 'Hospital Geral com cirurgia oncológica', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (151, 1, '1715', 'Serviço de radioterapia de complexo hospitalar', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (152, 1, '1716', 'Serviço de Oncologia Clínica de Complexo hospitalar', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (153, 1, '1717', 'Oncologia Cirúrgica Hospital Porte A', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (154, 1, '1718', 'Oncologia Cirúrgica Hospital Porte B.', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (155, 1, '1719', 'Serviço de Referência P/Diagnóstico e Trat. de Lesões Precursoras do Câncer do Colo de Útero(SRC)', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (156, 1, '1720', 'Serviço de Referência para Diagnóstico de Câncer de Mama (SDM)', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (157, 1, '1721', 'Hospital Geral com Cirurgia de Câncer de Complexo Hospitalar', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (158, 1, '1722', 'Tratamentos Integrados Sincrônicos em Oncologia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (159, 1, '1723', 'Reconstrução Mamária Pós-Mastectomia Total', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (160, 1, '1801', 'Centro de referência de tratamento de osteogênesis imperfecta', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (161, 1, '1901', 'Laqueadura', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (162, 1, '1902', 'Vasectomia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (163, 1, '2001', 'Programa de assistência ventilatoria não invasiva aos portadores de doenças neuromusculares', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (164, 1, '2101', 'Unidade de referência em assistência a queimados - média complexidade', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (165, 1, '2102', 'Centro de referência em assistência a queimados - alta complexidade', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (166, 1, '2201', 'Centro de referência de reabilitação em medicina fisica', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (167, 1, '2202', 'Centro de reabilitação fisica - nível intermediário', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (168, 1, '2203', 'Centro de Reabilitação Visual', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (169, 1, '2204', 'Centro de Reabilitação Auditiva na Média Complexidade', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (170, 1, '2205', 'Centro de Reabilitação Auditiva na Alta Complexidade', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (171, 1, '2206', 'Centro de Reabilitação Intelectual', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (172, 1, '2207', 'Centro de Reabilitação dos Transtornos do Spectro do Autismo', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (173, 1, '2208', 'Centro Especializado em Reabilitação (CER) Modalidade Física', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (174, 1, '2209', 'Centro Especializado em Reabilitação (CER) Modalidade Intelectual', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (175, 1, '2210', 'Centro Especializado em Reabilitação (CER) Modalidade Auditiva', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (176, 1, '2211', 'Centro Especializado em Reabilitação (CER) Modalidade Visual', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (177, 1, '2212', 'Oficina Ortopédica Fixa', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (178, 1, '2213', 'Oficina Ortopédica Intínerante', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (179, 1, '2301', 'Unidade de assistência de alta complexidade em terapia nutricional', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (180, 1, '2302', 'Centro de referência de alta complexidade em terapia nutricional', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (181, 1, '2303', 'Enteral', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (182, 1, '2304', 'Enteral e parenteral', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (183, 1, '2305', 'Enteral e parenteral com manipulação e fabricação da fórmula nutricional', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (184, 1, '2306', 'Nutrição enteral', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (185, 1, '2308', 'Serviço de Referência em Tratamento da Pessoa com Falência Intestinal', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (186, 1, '2401', 'Transplante de medula óssea-autogênico', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (187, 1, '2402', 'Transplante de medula óssea-alogênico aparentado', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (188, 1, '2403', 'Transplante de medula óssea-alogênico não aparentado', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (189, 1, '2404', 'Transplante de pâncreas', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (190, 1, '2405', 'Transplante conjugado rim e pâncreas', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (191, 1, '2407', 'Transplante de córnea/esclera', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (192, 1, '2408', 'Transplante de rim', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (193, 1, '2409', 'Transplante de fígado', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (194, 1, '2410', 'Transplante de pulmão', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (195, 1, '2411', 'Transplante de coração', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (196, 1, '2412', 'Busca ativa de orgãos', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (197, 1, '2413', 'Banco de tecido ocular humano', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (198, 1, '2414', 'Banco de válvulas cardíacas', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (199, 1, '2415', 'Banco de tecido músculo-esquelético', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (200, 1, '2416', 'Banco de sangue e cordão umbilical e placentário', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (201, 1, '2417', 'Exames de histocompatibilidade atraves de sorologia - Tipo I', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (202, 1, '2418', 'Exames de histocompatibilidade atraves de sorologia e ou biologia molecular - Tipo II', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (203, 1, '2419', 'Banco de Pele Humana', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (204, 1, '2420', 'Retirada de Órgãos e Tecidos', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (205, 1, '2421', 'Banco de Multitecidos', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (206, 1, '2422', 'Transplante de tecido músculo esquelético', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (207, 1, '2423', 'Transplante da válvula cardíaca humana', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (208, 1, '2424', 'Transplante de pele', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (209, 1, '2425', 'Cadastramento de doadores voluntários de medula óssea e outros precursores hematopoéticos', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (210, 1, '2426', 'Estabelecimento de saúde de Nível A', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (211, 1, '2427', 'Estabelecimento de saúde de Nível B', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (212, 1, '2428', 'Estabelecimento de saúde de Nível C', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (213, 1, '2429', 'Estabelecimento de saúde de Nível D', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (214, 1, '2430', 'Transplante de figado - IHH por febre amarela', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (215, 1, '2431', 'QUALIDOT Nível A', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (216, 1, '2432', 'QUALIDOT Nível B', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (217, 1, '2433', 'QUALIDOT Nível C', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (218, 1, '2434', 'QUALIDOT Nível D', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (219, 1, '2435', 'QUALIDOT Nível E', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (220, 1, '2436', 'Incremento Financeiro SNT TMO Nível A', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (221, 1, '2437', 'Incremento Financeiro SNT TMO Nível B', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (222, 1, '2438', 'Incremento Financeiro SNT TMO Nível C', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (223, 1, '2439', 'Incremento Financeiro SNT TMO Nível D', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (224, 1, '2440', 'Incremento Financeiro SNT TMO Nível E', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (225, 1, '2441', 'Incremento Financeiro SNT Pâncreas Nível A', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (226, 1, '2442', 'Incremento Financeiro SNT Pâncreas Nível B', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (227, 1, '2443', 'Incremento Financeiro SNT Pâncreas Nível C', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (228, 1, '2444', 'Incremento Financeiro SNT Pâncreas Nível D', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (229, 1, '2445', 'Incremento Financeiro SNT Pâncreas Nível E', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (230, 1, '2446', 'Incremento Financeiro SNT Rim Nível A', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (231, 1, '2447', 'Incremento Financeiro SNT Rim Nível B', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (232, 1, '2448', 'Incremento Financeiro SNT Rim Nível C', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (233, 1, '2449', 'Incremento Financeiro SNT Rim Nível D', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (234, 1, '2450', 'Incremento Financeiro SNT Rim Nível E', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (235, 1, '2451', 'Incremento Financeiro SNT Fígado Nível A', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (236, 1, '2452', 'Incremento Financeiro SNT Fígado Nível B', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (237, 1, '2453', 'Incremento Financeiro SNT Fígado Nível C', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (238, 1, '2454', 'Incremento Financeiro SNT Fígado Nível D', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (239, 1, '2455', 'Incremento Financeiro SNT Fígado Nível E', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (240, 1, '2456', 'Incremento Financeiro SNT Pulmão Nível A', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (241, 1, '2457', 'Incremento Financeiro SNT Pulmão Nível B', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (242, 1, '2458', 'Incremento Financeiro SNT Pulmão Nível C', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (243, 1, '2459', 'Incremento Financeiro SNT Pulmão Nível D', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (244, 1, '2460', 'Incremento Financeiro SNT Pulmão Nível E', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (245, 1, '2461', 'Incremento Financeiro SNT Coração Nível A', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (246, 1, '2462', 'Incremento Financeiro SNT Coração Nível B', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (247, 1, '2463', 'Incremento Financeiro SNT Coração Nível C', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (248, 1, '2464', 'Incremento Financeiro SNT Coração Nível D', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (249, 1, '2465', 'Incremento Financeiro SNT Coração Nível E', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (250, 1, '2501', 'Unidade de atenção especializada em traumato-ortopedia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (251, 1, '2502', 'Centro de referência de alta complexidade em traumato-ortopedia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (252, 1, '2503', 'Coluna', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (253, 1, '2504', 'Cintura escapular, ombro, braço e cotovelo', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (254, 1, '2505', 'Antebraço, punho e mão', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (255, 1, '2506', 'Cintura pélvica, quadril, coxa', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (256, 1, '2507', 'Coxa, joelho e perna', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (257, 1, '2508', 'Perna, tornozelo e pé', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (258, 1, '2509', 'Ortopedia infantil', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (259, 1, '2510', 'Traumatologia ortopédica de urgência', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (260, 1, '2511', 'Ortopedia - Coluna', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (261, 1, '2512', 'Ortopedia - Ombro', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (262, 1, '2513', 'Ortopedia - Mão', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (263, 1, '2514', 'Ortopedia - Quadril', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (264, 1, '2515', 'Ortopedia - Joelho', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (265, 1, '2516', 'Ortopedia - Tumor Ósseo', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (266, 1, '2517', 'Outros segmentos ósseos', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (267, 1, '2518', 'Adesão á Estratégia de Aumento do Acesso aos Procedimentos-TOM', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (268, 1, '2601', 'UTI II - Adulto', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (269, 1, '2602', 'UTI II - Neonatal', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (270, 1, '2603', 'UTI II - Pediátrica', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (271, 1, '2604', 'UTI III - Adulto', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (272, 1, '2605', 'UTI III - Neonatal', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (273, 1, '2606', 'UTI III - Pediátrica', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (274, 1, '2607', 'UTI - Queimados', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (275, 1, '2608', 'Unidade Terapia Intensiva Coronariana - UCO TIPO II', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (276, 1, '2609', 'Unidade Terapia Intensiva Coronariana - UCO TIPO III', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (277, 1, '2610', 'Unidade de Terapia Intensiva Neonatal Tipo II - UTIN II', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (278, 1, '2611', 'Unidade de Terapia Intensiva Neonatal Tipo III - UTIN III', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (279, 1, '2612', 'UTI II Adulto - Síndrome Respiratória Aguda Grave (SRAG) - COVID-19', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (280, 1, '2613', 'UTI II Pediátrica - Síndrome Respiratória Aguda Grave (SRAG) - COVID-19', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (281, 1, '2696', 'UTI I Adulto', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (282, 1, '2697', 'UTI I Neonatal', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (283, 1, '2698', 'UTI I Pediatria', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (284, 1, '2699', 'UTI I', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (285, 1, '2701', 'Hospital Tipo I em Urgência', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (286, 1, '2702', 'Hospital Tipo II em Urgência', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (287, 1, '2703', 'Hospital Tipo III em Urgência', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (288, 1, '2711', 'Administração Pré Hospitalar de Tenectoplase', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (289, 1, '2801', 'Unidade de cuidados intermediários neonatal', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (290, 1, '2802', 'Unidade de Cuidados Intermediários Neonatal Convencional (UCINCo)', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (291, 1, '2803', 'Unidade de Cuidados Intermediários Neonatal Canguru (UCINCa)', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (292, 1, '2804', 'Unidade de Cuidados Intermediários Adulto', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (293, 1, '2805', 'Unidade de Cuidados Intermediários Pediátrica (UCI-P)', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (294, 1, '2806', 'Leito de Suporte Ventilatório Pulmonar-COVID-19', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (295, 1, '2901', 'Videocirurgia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (296, 1, '2902', 'Programa Mais Acesso a Especialistas - Componente Cirurgias', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (297, 1, '3001', 'Unidade de Atenção Especializada no Processo Transexualizador', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (298, 1, '3002', 'Atenção ao Pré e Pós Operatório (clínico) e Hormonioterapia no Processo Transexualizador', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (299, 1, '3003', 'Atenção ao Pré e Pós Operatório e Cirurgias no Processo Transexualizador', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (300, 1, '3101', 'HPP- Hospital de Pequeno Porte', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (301, 1, '3201', 'Unidade de Mamografia Móvel', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (302, 1, '3202', 'Laboratório de Exames Citopatológico do Cólo do Últero-Tipo I', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (303, 1, '3203', 'Lab. Monitoramento Externo de Qualidade de Exame Citopatológico do Colo do Útero Tipo-II', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (304, 1, '3401', 'Centro de Trauma Tipo I', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (305, 1, '3402', 'Centro de Trauma Tipo II', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (306, 1, '3403', 'Centro de Trauma Tipo III', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (307, 1, '3501', 'Atenção Especializada Eixo I DR de Origem Genética: 1-Anomalias Congênitas ou de Manifestação Tardia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (308, 1, '3502', 'Atenção Especializada Eixo I DR de Origem Genética:2-Deficiência Intelectual Associada à Doença Rara', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (309, 1, '3503', 'Atenção Especializada Eixo I DR de Origem Genética: 3-Erro Inato do Metabolismo (EIM)', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (310, 1, '3504', 'Atenção Especializada Eixo II DR de Origem não Genética: 1-Doenças Raras Inflamatórias', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (311, 1, '3505', 'Atenção Especializada Eixo II DR de Origem não Genética: 2-Doenças Raras Infecciosas', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (312, 1, '3506', 'Atenção Especializada Eixo II DR de Origem não Genética: 3-Doenças Raras Autoimunes', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (313, 1, '3507', 'Serviço de Referência Eixo I DR de Origem Genética:1 Anomalias Congênitas ou de Manifestação Tardia', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (314, 1, '3508', 'Serviço de Referência Eixo I DR de Origem Genética:2-Deficiência Intelectual Associada à Doença Rara', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (315, 1, '3509', 'Serviço de Referência Eixo I DR de Origem Genética:3-Erro Inato do Metabolismo (EIM)', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (316, 1, '3510', 'Serviço de Referência Eixo II DR de Origem não Genética:3-Doenças Raras Autoimunes', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (317, 1, '3511', 'Serviço de Referência Eixo II DR de Origem não Genética:2-Doenças Raras Inflamatórias', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (318, 1, '3512', 'Serviço de Referência Eixo II DR de Origem não Genética:1-Doenças Raras Infecciosas', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (319, 1, '3513', 'Atenção Especializada Eixo II DR de Origem não Genética:4-Outras DR de Origem não Genética', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (320, 1, '3514', 'Serviço de Referência Eixo II DR de Origem não Genética:4-Outras DR de Origem não Genética', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (321, 1, '3515', 'Serviço de Aconselhamento Genético', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (322, 1, '3601', 'Sítio Testador de ácidos nucléicos (SIT-NAT)', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (323, 1, '3701', 'Coleta de Vestígios de Violência Sexual', '202504');
INSERT INTO tb_habilitacao (id, version_id, co_habilitacao, no_habilitacao, dt_competencia) VALUES (324, 1, '3801', 'Programa Mais Acesso a Especialistas', '202504');
