-- Script SQL INSERT para a tabela: tb_renases
-- Gerado a partir do arquivo de dados: tb_renases.txt (Encoding Leitura: latin-1)
-- Usando version_id: 1
-- Data de geração: 2025-05-12 21:55:55

INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (1, 1, '001', 'Gestão da Atenção Primária');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (2, 1, '002', 'Atenção Domiciliar');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (3, 1, '003', 'Atendimento Cirúrgico Ambulatorial Básico');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (4, 1, '004', 'Atendimento Clinico na Atenção Primária');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (5, 1, '005', 'Consulta e Acompanhamento Realizados por Profissional de Nível Superior');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (6, 1, '006', 'Exames Diagnósticos na Atenção Primária');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (7, 1, '007', 'Práticas Integrativas e Complementares');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (8, 1, '008', 'Ações Comunitárias');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (9, 1, '009', 'Atenção Familiar');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (10, 1, '010', 'Atividades Educativas, Terapêuticas e de Orientação à População.');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (11, 1, '011', 'Atividades Físicas, Educativas e de Orientação à População.');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (12, 1, '012', 'Imunização');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (13, 1, '013', 'Visita Domiciliar ou Institucional');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (14, 1, '014', 'Atenção à Saúde da Criança');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (15, 1, '015', 'Atenção à Saúde da Mulher');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (16, 1, '016', 'Atenção à Saúde de Pessoas com Doenças Transmissíveis Epidemiologicamente Relevantes para o País');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (17, 1, '017', 'Atenção à Saúde do Adolescente');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (18, 1, '018', 'Atenção à Saúde do Homem');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (19, 1, '019', 'Atenção à Saúde do Idoso');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (20, 1, '020', 'Atenção à Saúde dos Adultos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (21, 1, '021', 'Atenção a Saúde Mental, Ácool e Outras Drogas');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (22, 1, '022', 'Educação em Saúde sobre Uso Racional de Medicamentos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (23, 1, '023', 'Orientação Farmacêutica na Dispensação de Medicamentos.');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (24, 1, '024', 'Realização de Procedimentos Cirúrgicos  em Saúde Bucal');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (25, 1, '025', 'Realização de Procedimentos Clínicos em Saúde Bucal');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (26, 1, '026', 'Atenção à Saúde da Pessoa com Deficiência');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (27, 1, '027', 'Gestão de Serviços de Urgência e Emergência');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (28, 1, '028', 'Atendimento de Urgência em Unidades Básicas de Saúde');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (29, 1, '029', 'Atendimento de Urgência em Unidades de Pronto Atendimento 24 horas');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (30, 1, '030', 'Atendimento de Urgência em Unidades Hospitalares');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (31, 1, '031', 'Atendimento em Sala de Estabilização');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (32, 1, '032', 'Atendimento Pré-hospitalar de Urgência para Gestantes, Puérperas e Recém-Nascidos de Alto Risco');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (33, 1, '033', 'Atendimento Pré-hospitalar Móvel de Urgência');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (34, 1, '034', 'Gestão da Rede de Atenção Psicossocial');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (35, 1, '035', 'Acolhimento e Atenção de Retaguarda para Usuários de Àlcool e Drogas');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (36, 1, '036', 'Alta Planejada e Reabilitação Psicossocial Assistida');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (37, 1, '037', 'Aplicação de Testes (psicodiagnósticos)');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (38, 1, '038', 'Atenção Psicossocial - Centros de Atenção Psicossocial');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (39, 1, '039', 'Atenção Psicossocial Hospitalar');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (40, 1, '040', 'Atividades Educativas Coletivas');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (41, 1, '041', 'Diagnóstico em Psicologia e Psiquiatria');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (42, 1, '042', 'Geração de Trabalho e Renda');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (43, 1, '043', 'Residências Terapêuticas para Egressos de Hospitais Psiquiátricos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (44, 1, '044', 'Terapia em Grupo');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (45, 1, '045', 'Terapia Individual');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (46, 1, '046', 'Tratamento dos Transtornos Mentais e Comportamentais');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (47, 1, '047', 'Gestão da Atenção Especializada');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (48, 1, '048', 'Acompanhamento e Tratamento de Doenças ou Condições Clínicas Crônicas');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (49, 1, '049', 'Assistência Domiciliar Terapêutica Multiprofissional em HIV/AIDS (ADTM)');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (50, 1, '050', 'Assistência Especializada Domiciliar Realizada por Equipe Multiprofissional');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (51, 1, '051', 'Atenção à Saúde de Pessoas Privadas de Liberdade');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (52, 1, '052', 'Atendimento e Acompanhamento de Pacientes Acometidos por Anemia Falciforme e Outras Hemoglobinopatias');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (53, 1, '053', 'Atendimento e Acompanhamento de Pacientes Acometidos por Doeças Endócrinas, Metabólicas ou Nutricionais');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (54, 1, '054', 'Atendimento e acompanhamento de pacientes com depressão pós-parto');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (55, 1, '055', 'Atendimento e Acompanhamento em Reabilitação de Pessoas com Deficiência');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (56, 1, '056', 'Atividade Educativa ou Orientação em Grupo na Atenção Especializada');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (57, 1, '057', 'Cirurgia Ambulatorial do Sistema Geniturinário: Vasectomia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (58, 1, '058', 'Cirurgias Ambulatoriais com Anestesia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (59, 1, '059', 'Cirurgias Ambulatoriais do Sistema Geniturinário');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (60, 1, '060', 'Cirurgias Ambulatoriais do Sistema Osteomuscular');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (61, 1, '061', 'Cirurgias Ambulatoriais em Nefrologia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (62, 1, '062', 'Cirurgias Ambulatoriais: Aparelho Digestivo, Orgãos Anexos e Parede Abdominal');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (63, 1, '063', 'Cirurgias Ambulatoriais: Cirurgia Bucomaxilofacial');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (64, 1, '064', 'Cirurgias Ambulatoriais: Cirurgia do Aparelho Circulatório');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (65, 1, '065', 'Cirurgias Ambulatoriais: Cirurgia Ginecológica e Obstétrica');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (66, 1, '066', 'Cirurgias Ambulatoriais: Cirurgia Plástica Reparadora');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (67, 1, '067', 'Cirurgias Ambulatoriais: Cirurgia Torácica');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (68, 1, '068', 'Cirurgias Ambulatoriais: Cirurgias da Mama');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (69, 1, '069', 'Cirurgias Ambulatoriais: Cirurgias Reparadoras para Tratamentos de Grandes Queimados e Pacientes com Lipoatrofia de Face');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (70, 1, '070', 'Cirurgias Ambulatoriais: Oftalmológicas');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (71, 1, '071', 'Cirurgias Ambulatoriais: Pele, Tecidos Subcutâneos e Mucosas');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (72, 1, '072', 'Cirurgias Ambulatoriais: Vias Respiratórias');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (73, 1, '073', 'Coleta de Material para Exame Complementar ao Diagnóstico, por Meio de Punção ou Biópsia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (74, 1, '074', 'Consultas Eletivas Especializadas, Realizadas por Profissionais de Nível Superior');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (75, 1, '075', 'Diagnóstico por Endoscopia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (76, 1, '076', 'Diagnóstico por Imagem');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (77, 1, '077', 'Diagnóstico por Medicina Nuclear IN VIVO');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (78, 1, '078', 'Diagnóstico por Radiologia Intervencionista');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (79, 1, '079', 'Diagnósticos e Procedimentos Especiais em Hemoterapia: Exames do Doador/Receptor');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (80, 1, '080', 'Diagnósticos e Procedimentos Especiais em Hemoterapia: Procedimentos Especiais em Hemoterápica');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (81, 1, '081', 'Diagnósticos por Testes Rápidos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (82, 1, '082', 'Dispensação de Òrteses e Próteses em Caráter Ambulatorial');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (83, 1, '083', 'Exames Anatomopatológicos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (84, 1, '084', 'Exames Citopatológicos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (85, 1, '085', 'Exames Citopatológicos para Prevenção do Câncer do Colo Uterino');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (86, 1, '086', 'Exames Complementares de Diagnóstico: Exames Bioquímicos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (87, 1, '087', 'Exames Complementares de Diagnóstico: Exames Coprológicos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (88, 1, '088', 'Exames Complementares de Diagnóstico: Exames de Uroanálise');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (89, 1, '089', 'Exames Complementares de Diagnóstico: Exames Hematológicos e Hemostasia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (90, 1, '090', 'Exames Complementares de Diagnóstico: Exames Microbiológicos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (91, 1, '091', 'Exames Complementares de Diagnóstico: Exames para Triagem Neonatal');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (92, 1, '092', 'Exames Complementares de Diagnóstico: Exames Sorológicos e Imunológicos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (93, 1, '093', 'Exames Complementares do Diagnóstico  - Exames em  Liquidos Biológicos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (94, 1, '094', 'Exames Complementares do Diagnóstico: Exames de Genética');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (95, 1, '095', 'Exames Complementares do Diagnóstico: Exames Imuno-Hematológicos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (96, 1, '096', 'Exames Hormonais');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (97, 1, '097', 'Exames Toxicológicos ou de Monitorização Terapêutica');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (98, 1, '098', 'Hemoterapia: Medicina Transfusional');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (99, 1, '099', 'Hemoterapia: Procedimentos Destinados à Obtenção do Sangue para Fins de Assistência Hemoterápica');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (100, 1, '100', 'Métodos Diagnósticos Cinético-Funcionais');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (101, 1, '101', 'Métodos Diagnósticos em Angiologia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (102, 1, '102', 'Métodos Diagnósticos em Cardiologia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (103, 1, '103', 'Métodos Diagnósticos em Cardiologia Intervencionista');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (104, 1, '104', 'Métodos Diagnósticos em Ginecologia e Obstetrícia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (105, 1, '105', 'Métodos Diagnósticos em Neurologia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (106, 1, '106', 'Métodos Diagnósticos em Oftalmologia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (107, 1, '107', 'Métodos Diagnósticos em Otorrinolaringologia e Fonoaudiologia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (108, 1, '108', 'Métodos Diagnósticos em Pneumologia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (109, 1, '109', 'Métodos diagnósticos em psicologia e psiquiatria');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (110, 1, '110', 'Métodos Diagnósticos em Urologia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (111, 1, '111', 'Outras Cirurgias Ambulatoriais');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (112, 1, '112', 'Terapia Nutricional');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (113, 1, '113', 'Terapias em doenças alérgicas');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (114, 1, '114', 'Terapias em Urologia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (115, 1, '115', 'Tratamento em Nefrologia: Tratamento Dialítico');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (116, 1, '116', 'Tratamento Oncológico: Medicina Nuclear - Terapêutica Oncológica');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (117, 1, '117', 'Tratamento Oncológico: Quimioterapia Adjuvante Profilática em Adultos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (118, 1, '118', 'Tratamento Oncológico: Quimioterapia Curativa em Adultos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (119, 1, '119', 'Tratamento Oncológico: Quimioterapia de Tumores de Crianças e Adolescentes');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (120, 1, '120', 'Tratamento Oncológico: Quimioterapia Paliativa em Adultos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (121, 1, '121', 'Tratamento Oncológico: Quimioterapia para Controle Temporário de Doença em Adultos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (122, 1, '122', 'Tratamento Oncológico: Quimioterapia Prévia Neoadjuvante ou Citorredutora em Adultos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (123, 1, '123', 'Tratamento Oncológico: Radioterapia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (124, 1, '124', 'Tratamento Oncológico: Tratamento de Intercorrências Clínicas em Paciente Oncológico');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (125, 1, '125', 'Realização de Procedimentos Clínicos em Odontologia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (126, 1, '126', 'Realização de procedimentos com finalidade diagnóstica em Odontologia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (127, 1, '127', 'Realização de Procedimentos Cirúrgicos em Odontologia Especializada');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (128, 1, '128', 'Atividade Educativa em Saúde Bucal');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (129, 1, '129', 'Confecção de Órteses e Próteses Odontológicas');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (130, 1, '130', 'Laboratório Regional de Prótese Dentária');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (131, 1, '131', 'Centro de Especialidade Odontológica');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (132, 1, '132', 'Atendimento Odontológico para Pacientes com Necessidades Especiais em Ambientes Hospitalares');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (133, 1, '133', 'Cirurgia do Sistema Osteomuscular');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (134, 1, '134', 'Cirurgia Bucomaxilofacial');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (135, 1, '135', 'Cirurgias Plásticas/Reparadoras');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (136, 1, '136', 'Cirurgia Reparadora para Lipodistrofia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (137, 1, '137', 'Cirurgia Reparadora em Tratamento de Queimados');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (138, 1, '138', 'Cirurgia Geral');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (139, 1, '139', 'Cirurgias em  Politraumatizados');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (140, 1, '140', 'Internações de Longa Permanência');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (141, 1, '141', 'Hospital-Dia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (142, 1, '142', 'Cirurgia em Oncologia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (143, 1, '143', 'Intervenções Cirúrgicas para Criação de Acessos para Diálise');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (144, 1, '144', 'Transplantes');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (145, 1, '145', 'Ações Relacionadas a Doação de Orgãos e Tecidos em Doador');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (146, 1, '146', 'Dispensação de Órteses e Próteses e Materiais Especiais em Caráter Hospitalar');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (147, 1, '147', 'Tratamento Intensivo');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (148, 1, '148', 'Acolhimento com Classificação de Risco em Maternidades');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (149, 1, '149', 'Parto Normal em Gravidez de Risco Habitual');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (150, 1, '150', 'Parto Normal em Gestação de Alto Risco');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (151, 1, '151', 'Parto Cesáreo em Gravidez de Risco Habitual');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (152, 1, '152', 'Parto Cesáreo em Gestação de Alto Risco');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (153, 1, '153', 'Parto Cesáreo com Laqueadura Tubária');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (154, 1, '154', 'Cirurgia Bariátrica');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (155, 1, '155', 'Internação para Tratamento Medicamentoso da Osteogenesis Imperfecta');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (156, 1, '156', 'Cirurgia do Sistema Nervoso Central e Periférico Relacionada ao Trauma e Anomalias do Desenvolvimento');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (157, 1, '157', 'Cirurgia do Sistema Nervoso Central e Periférico Relacionada a Coluna e Nervos Periféricos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (158, 1, '158', 'Cirurgia do Sistema Nervoso Central e Periférico Relacionada aos Tumores do Sistema Nervoso');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (159, 1, '159', 'Cirurgia do Sistema Nervoso Central e Periférico, Relacionada às Neurocirurgias Vasculares');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (160, 1, '160', 'Cirurgia do Sistema Nervoso Central e Periférico, Relacionada ao Tratamento Neurocirúrgico da Dor Funcional');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (161, 1, '161', 'Cirurgia do Sistema Nervoso Central: Investigação e Cirurgia da Epilepsia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (162, 1, '162', 'Cirurgia do Sistema Nervoso Central e Periférico, Relacionada ao Tratamento Neuroendovascular');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (163, 1, '163', 'Cirurgia das Vias Aéreas Superiores, da Face, da Cabeça e do Pescoço');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (164, 1, '164', 'Cirurgia do Aparelho da Visão');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (165, 1, '165', 'Cirurgia Cardiovascular');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (166, 1, '166', 'Cirurgia Vascular');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (167, 1, '167', 'Cardiologia Intervencionista');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (168, 1, '168', 'Cirurgia Endovascular');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (169, 1, '169', 'Eletrofisiologia');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (170, 1, '170', 'Cirurgia do Sistema Nervoso Central - Neurocirurgia Funcional Estereotáxica');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (171, 1, '171', 'Gestão da Vigilância em Saúde');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (172, 1, '172', 'Autorização de Funcionamento de Empresas sujeitas a Vigilância Sanitária');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (173, 1, '173', 'Registro, Notificação, Cadastro Sanitário de Produtos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (174, 1, '174', 'Anuência de Importação e Registro de Exportação');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (175, 1, '175', 'Anuência Prévia de Patente');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (176, 1, '176', 'Regulação de Preço de Medicamentos e Produtos para Saúde');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (177, 1, '177', 'Credenciamento e Habilitação de Laboratórios Analíticos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (178, 1, '178', 'Controle Sanitário e Orientação de Viajantes');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (179, 1, '179', 'Monitoramento Sanitário de Produtos e Serviços');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (180, 1, '180', 'Gerenciamento do Risco Sanitário');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (181, 1, '181', 'Análise e Aprovação de Projetos Básicos de Arquitetura');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (182, 1, '182', 'Informação, Educação e Comunicação em Vigilância em Saúde');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (183, 1, '183', 'Acolhimento e Atendimento a Notificações, Denuncias e Reclamações');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (184, 1, '184', 'Regulamentação de Ações de Saúde Pública sob Vigilância Sanitária');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (185, 1, '185', 'Fiscalização Sanitária de Produtos e Serviços');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (186, 1, '186', 'Emissão de Certidões e Certificados');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (187, 1, '187', 'Inspeção Sanitária dos Estabelecimentos Sujeitos à Vigilância Sanitária');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (188, 1, '188', 'Emissão de Licença Sanitária para Estabelecimentos Sujeitos à Vigilância Sanitária');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (189, 1, '189', 'Farmacovigilância');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (190, 1, '190', 'Alerta e Resposta a Surtos e Eventos de Importância em Saúde Pública');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (191, 1, '191', 'Notificação de Eventos de Interesse de Saúde Pública');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (192, 1, '192', 'Investigação de Eventos de Interesse de Saúde Pública');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (193, 1, '193', 'Busca Ativa');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (194, 1, '194', 'Interrupção da Cadeia de Transmissão');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (195, 1, '195', 'Controle de Vetores, Reservatórios e Hospedeiros.');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (196, 1, '196', 'Diagnóstico Laboratorial de Eventos de Interesse de Saúde Pública');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (197, 1, '197', 'Vacinação');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (198, 1, '198', 'Oferta de Tratamento Clínico e Cirúrgico para Doenças de Interesse de Saúde Pública');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (199, 1, '199', 'Realização de Inquéritos Epidemiológicos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (200, 1, '200', 'Prevenção de Doenças e Agravos');
INSERT INTO tb_renases (id, version_id, co_renases, no_renases) VALUES (201, 1, '201', 'Promoção da Saúde');
