-- Script SQL INSERT para a tabela: tb_servico
-- Gerado a partir do arquivo de dados: tb_servico.txt (Encoding Leitura: latin-1)
-- Usando version_id: 1
-- Data de geração: 2025-05-12 21:55:55

INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (1, 1, '100', 'Serviço de Atenção a Saúde no Sistema Penitenciário', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (2, 1, '101', 'Estratégia de Saúde da Família', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (3, 1, '102', 'Estratégias de Agentes Comunitário de Saúde', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (4, 1, '103', 'Serviço de Atendimento Móvel de Urgências', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (5, 1, '104', 'Regulação Assistêncial dos Serviços de Saúde', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (6, 1, '105', 'Serviço de Atenção em Neurologia/ Neurocirurgia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (7, 1, '106', 'Serviço de Atenção a DST/HIV/AIDS', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (8, 1, '107', 'Atenção à Saúde Auditiva', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (9, 1, '108', 'Atenção a Saúde do Trabalhador', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (10, 1, '109', 'Serviço de Atenção a Saúde dos Adolecentes em Conflito com a Lei, em Regime de Internação e Internação Provisória', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (11, 1, '110', 'Serviço de Atenção a Saúde Reprodutiva', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (12, 1, '111', 'Serviço de Atenção ao Paciente com Tuberculose', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (13, 1, '112', 'Serviço de Atenção ao Pré-Natal e Nascimento', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (14, 1, '113', 'Serviço de Atenção Domiciliar', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (15, 1, '114', 'Serviço de Atenção em Saúde Bucal', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (16, 1, '115', 'Serviço de Atenção Psicossocial', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (17, 1, '116', 'Serviço de Atenção Cardiovascular/Cardiologia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (18, 1, '117', 'Serviço de Cirurgia Reparadora', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (19, 1, '118', 'Serviço de Cirurgia Torácica', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (20, 1, '119', 'Serviço de Controle de Tabagismo', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (21, 1, '120', 'Serviço de Diagnóstico por Anatomia Patológica e/ou Citopatologia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (22, 1, '121', 'Diagnóstico por Imagem', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (23, 1, '122', 'Serviço de Diagnóstico por Métodos Gráficos/Dinâmicos', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (24, 1, '123', 'Serviço de Dispensação de Órteses, Próteses e Materiais Especiais', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (25, 1, '124', 'Serviço de Endocrinologia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (26, 1, '125', 'Serviço de Farmácia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (27, 1, '126', 'Serviço de Fisioterapia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (28, 1, '127', 'Serviço de Atenção à Obesidade', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (29, 1, '128', 'Serviço de Hemoterapia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (30, 1, '129', 'Servico de Laboratório de Histocompatibilidade', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (31, 1, '130', 'Atenção à Doença Renal Crônica', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (32, 1, '131', 'Serviço de Oftalmologia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (33, 1, '132', 'Serviço de Oncologia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (34, 1, '133', 'Serviço de Pneumologia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (35, 1, '134', 'Serviço de Práticas Integrativas e Complementares', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (36, 1, '135', 'Serviço de Reabilitação', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (37, 1, '136', 'Serviço de Suporte Nutricional', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (38, 1, '137', 'Serviço de Telemedicina', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (39, 1, '138', 'Serviço de Traumato-Ortopedia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (40, 1, '139', 'Serviço de Triagem Neonatal', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (41, 1, '140', 'Serviço de Urgência e Emergência', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (42, 1, '141', 'Serviço de Vigilância em Saúde', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (43, 1, '142', 'Serviço de Endoscopia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (44, 1, '143', 'Serviço Móvel de Urgência (exceto SAMU)', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (45, 1, '144', 'Serviço Posto de Coleta de Materiais Biológicos', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (46, 1, '145', 'Serviço de Diagnóstico por Laboratório Clínico', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (47, 1, '146', 'Serviço de Videolaparoscopia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (48, 1, '147', 'Serviço de Apoio a Saúde da Família', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (49, 1, '148', 'Hospital-Dia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (50, 1, '149', 'Transplante', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (51, 1, '150', 'Cirurgia Vascular', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (52, 1, '151', 'Medicina Nuclear', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (53, 1, '152', 'Atenção à Saúde da População Indígena', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (54, 1, '153', 'Atenção Especializada no Processo Transexualizador', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (55, 1, '154', 'Serviço de Banco de Tecidos', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (56, 1, '155', 'Serviço de Traumatologia  Ortopedia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (57, 1, '157', 'Serviço de Laboratorio de Protese Dentaria', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (58, 1, '158', 'Serviço de Atenção Integral em Hanseniase', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (59, 1, '159', 'Atenção Primária', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (60, 1, '160', 'Teleconsultoria', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (61, 1, '161', 'Consultório na Rua', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (62, 1, '162', 'Serviço de Terapia Intensiva', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (63, 1, '163', 'Serviço de Cuidados Intermediários', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (64, 1, '164', 'Serviço de Órteses,Próteses e Materiais Especiais em Reabilitação', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (65, 1, '165', 'Atenção às Pessoas em Situação de Violência Sexual', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (66, 1, '166', 'Serviço de  Análise Laboratorial  de Produtos Sujeitos á  Vigilância Sanitária', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (67, 1, '167', 'Atendimento Itinerante de Asistência e Ensino em Saúde', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (68, 1, '168', 'Atenção Às Pessoas com Doenças Raras', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (69, 1, '169', 'Serviço de Atenção em Urologia', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (70, 1, '170', 'Comissões e Comitês', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (71, 1, '171', 'Cuidados Paliativos', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (72, 1, '173', 'Logística de Imunobiológicos', '202504');
INSERT INTO tb_servico (id, version_id, co_servico, no_servico, dt_competencia) VALUES (73, 1, '174', 'Imunização', '202504');
